from django.contrib import admin
from .models import *


admin.site.register(Provider)
admin.site.register(StockType)
admin.site.register(StockSupply)
admin.site.register(Stock)
admin.site.register(Warehouse)
admin.site.register(Palette)
admin.site.register(Order)
admin.site.register(Delivery)
admin.site.register(DeliveryItem)
admin.site.register(DeliveryPalette)
admin.site.register(Product)
admin.site.register(WarehouseStock)
admin.site.register(OrderSettlement)
admin.site.register(OrderSettlementProduct)
admin.site.register(WarehouseStockHistory)
# admin.site.register(ProductSell)
admin.site.register(MonthResults)
# admin.site.register(ProductSell2)
# admin.site.register(CustomerDelivery)
# admin.site.register(DeliveryCustomerPalette)
# admin.site.register(DeliverySell)
admin.site.register(CustomerPalette)
admin.site.register(ProductSell3)
admin.site.register(ProductComplexParts)
admin.site.register(ProductComplexAssembly)
admin.site.register(DeliverySpecial)
admin.site.register(DeliverySpecialItem)
admin.site.register(OrderToOrderShift)
admin.site.register(PriceList)
admin.site.register(PriceListItem)
admin.site.register(StockSupplySettlement)
admin.site.register(StockSupplySell)
