# Generated by Django 3.1.1 on 2020-09-20 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehousemanager', '0002_auto_20200920_1446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyer',
            name='employers',
            field=models.ManyToManyField(blank=True, to='warehousemanager.Person'),
        ),
        migrations.AlterField(
            model_name='cardboardprovider',
            name='employers',
            field=models.ManyToManyField(blank=True, to='warehousemanager.Person'),
        ),
    ]
