# Generated by Django 3.1.1 on 2020-09-20 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehousemanager', '0003_auto_20200920_1448'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='buyer',
            field=models.ManyToManyField(blank=True, to='warehousemanager.Buyer'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='dimension_three',
            field=models.IntegerField(blank=True, default=0),
            preserve_default=False,
        ),
    ]
