# Generated by Django 3.1.1 on 2020-09-20 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehousemanager', '0004_auto_20200920_1451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='dimension_three',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
