# Generated by Django 3.1.1 on 2020-09-20 17:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('warehousemanager', '0005_auto_20200920_1452'),
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_delivery', models.DateField()),
            ],
        ),
        migrations.AddField(
            model_name='orderitem',
            name='ordered_quantity',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='OrderItemQuantity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('delivery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehousemanager.delivery')),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehousemanager.orderitem')),
            ],
        ),
        migrations.AddField(
            model_name='delivery',
            name='items',
            field=models.ManyToManyField(through='warehousemanager.OrderItemQuantity', to='warehousemanager.OrderItem'),
        ),
        migrations.AddField(
            model_name='delivery',
            name='provider',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='warehousemanager.cardboardprovider'),
        ),
    ]
