# Generated by Django 3.1.1 on 2020-09-21 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehousemanager', '0006_auto_20200920_1758'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='delivery',
            name='provider',
        ),
        migrations.AddField(
            model_name='delivery',
            name='provider',
            field=models.ManyToManyField(to='warehousemanager.CardboardProvider'),
        ),
        migrations.RemoveField(
            model_name='order',
            name='provider',
        ),
        migrations.AddField(
            model_name='order',
            name='provider',
            field=models.ManyToManyField(to='warehousemanager.CardboardProvider'),
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='order',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='order',
            field=models.ManyToManyField(to='warehousemanager.Order'),
        ),
    ]
