# Generated by Django 3.1.1 on 2020-09-21 03:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('warehousemanager', '0008_auto_20200921_0301'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='delivery',
            name='provider',
        ),
        migrations.AddField(
            model_name='delivery',
            name='provider',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='warehousemanager.cardboardprovider'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='order',
            name='provider',
        ),
        migrations.AddField(
            model_name='order',
            name='provider',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='warehousemanager.cardboardprovider'),
            preserve_default=False,
        ),
    ]
