# Generated by Django 3.1.1 on 2020-09-22 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehousemanager', '0009_auto_20200921_0310'),
    ]

    operations = [
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('shortcut', models.CharField(max_length=8)),
            ],
        ),
        migrations.AlterField(
            model_name='order',
            name='order_provider_number',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='item_number',
            field=models.IntegerField(),
        ),
    ]
