# Generated by Django 3.1.1 on 2020-09-23 03:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warehousemanager', '0011_order_is_completed'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderitem',
            options={'ordering': ['item_number']},
        ),
    ]
