# Generated by Django 3.1.2 on 2020-10-26 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehousemanager', '0012_auto_20200923_0314'),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_date', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(default='Note', max_length=32)),
                ('content', models.TextField()),
            ],
        ),
    ]
