# Generated by Django 3.1.2 on 2020-10-30 21:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('warehousemanager', '0014_note_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='genre',
            field=models.CharField(choices=[('Ordinary', 'Ordinary'), ('To Do List', 'To Do List'), ('Journal', 'Journal'), ('Notice', 'Notice')], default='Ordinary', max_length=16),
        ),
        migrations.CreateModel(
            name='Absence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('absence_date', models.DateField()),
                ('absence_type', models.CharField(choices=[('NN', 'Nieobecność nieusprawiedliwiona'), ('UW', 'Urlop wypoczynkowy'), ('UO', 'Urlop okolicznościowy'), ('SP', 'Spóźnienie'), ('UB', 'Urlop bezpłatny')], max_length=4)),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehousemanager.person')),
            ],
        ),
    ]
