# Generated by Django 3.1.2 on 2020-11-03 17:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehousemanager', '0016_auto_20201103_0431'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buyer',
            name='employers',
        ),
        migrations.RemoveField(
            model_name='cardboardprovider',
            name='employers',
        ),
        migrations.AddField(
            model_name='person',
            name='job_end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='job_start',
            field=models.DateField(default=datetime.datetime(2017, 1, 1, 0, 0)),
        ),
    ]
