# Generated by Django 3.1.2 on 2020-11-06 04:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('warehousemanager', '0017_auto_20201103_1811'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtraHour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('quantity', models.DecimalField(decimal_places=1, max_digits=3)),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehousemanager.person')),
            ],
        ),
    ]
