# Generated by Django 3.1.2 on 2020-11-07 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehousemanager', '0021_punch_type_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='punch',
            name='type_num',
            field=models.CharField(max_length=8),
        ),
    ]
