# Generated by Django 3.1.2 on 2020-11-09 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehousemanager', '0023_punch_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='punch',
            name='name',
            field=models.CharField(blank=True, default='', max_length=24),
        ),
    ]
