# Generated by Django 3.1.2 on 2020-11-09 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehousemanager', '0024_auto_20201109_0509'),
    ]

    operations = [
        migrations.AddField(
            model_name='punch',
            name='type_letter',
            field=models.CharField(blank=True, default='', max_length=4),
        ),
        migrations.AlterField(
            model_name='punch',
            name='type_num',
            field=models.CharField(blank=True, default='', max_length=4),
        ),
    ]
