# Generated by Django 3.1.2 on 2020-11-09 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehousemanager', '0025_auto_20201109_1821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='punch',
            name='type_num',
            field=models.DecimalField(decimal_places=1, max_digits=4),
        ),
    ]
