# Generated by Django 3.1.2 on 2020-11-09 19:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('warehousemanager', '0027_auto_20201109_2016'),
    ]

    operations = [
        migrations.AddField(
            model_name='punchproduction',
            name='worker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='warehousemanager.person'),
        ),
    ]
