# Generated by Django 3.1.2 on 2020-11-12 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehousemanager', '0029_auto_20201112_0412'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardboardprovider',
            name='shortcut',
            field=models.CharField(blank=True, max_length=6),
        ),
    ]
