# Generated by Django 3.1.2 on 2020-12-16 16:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('warehousemanager', '0029_auto_20201112_0412'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpreadsheetCopy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gs_id', models.CharField(max_length=48)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='buyer',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='cardboardprovider',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='delivery',
            options={'ordering': ['date_of_delivery']},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['date_of_order', 'order_provider_number']},
        ),
        migrations.AlterModelOptions(
            name='orderitem',
            options={'ordering': ['order__provider__name', 'order__order_provider_number', 'item_number']},
        ),
        migrations.AlterModelOptions(
            name='person',
            options={'ordering': ['last_name', 'first_name']},
        ),
        migrations.AddField(
            model_name='buyer',
            name='shortcut',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='cardboardprovider',
            name='shortcut',
            field=models.CharField(blank=True, max_length=6),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='cardboard_additional_info',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='name',
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.AlterField(
            model_name='machine',
            name='shortcut',
            field=models.CharField(max_length=16),
        ),
        migrations.AlterField(
            model_name='order',
            name='date_of_order',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='cardboard_type',
            field=models.CharField(choices=[('3B', '3B'), ('3C', '3C'), ('3E', '3E'), ('5BC', '5BC'), ('5EB', '5EB'), ('BB', 'BB'), ('BCS', 'BCS'), ('BS', 'BS')], max_length=8),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='sort',
            field=models.CharField(choices=[('201', 'FEFCO 201'), ('202', 'FEFCO 202'), ('203', 'FEFCO 203'), ('301', 'FEFCO 301'), ('SZTANCA', 'Sztanca'), ('PRZEKLADKA', 'Przekładka'), ('MAG', 'Magazyn'), ('ROT/TYG', 'Rotacja/Tygiel')], max_length=15),
        ),
        migrations.AlterField(
            model_name='punch',
            name='cardboard',
            field=models.CharField(choices=[('3B', '3B'), ('3C', '3C'), ('3E', '3E'), ('5BC', '5BC'), ('5EB', '5EB'), ('BB', 'BB'), ('BCS', 'BCS'), ('BS', 'BS')], max_length=4),
        ),
        migrations.CreateModel(
            name='ProductionProcess',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('KLSD', 'KLEJENIE-SKLEJARKA-DUŻA'), ('KLSM', 'KLEJENIE-SKLEJARKA-MAŁA'), ('KLR', 'KLEJENIE-RĘCZNE'), ('DR', 'DRUKOWANIE'), ('WY', 'WYCINANIE'), ('WY+DR', 'WYCINANIE Z NADRUKIEM'), ('SZ', 'SZTANCOWANIE'), ('OB', 'OBRYWANIE'), ('PK', 'PAKOWANIE'), ('INNE', 'INNE')], max_length=8)),
                ('quantity_start', models.IntegerField()),
                ('quantity_end', models.IntegerField()),
                ('date_start', models.DateField()),
                ('date_end', models.DateField()),
                ('machine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='warehousemanager.machine')),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehousemanager.orderitem')),
                ('production', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='warehousemanager.productionprocess')),
                ('punch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='warehousemanager.punch')),
                ('stock', models.ManyToManyField(to='warehousemanager.OrderItemQuantity')),
                ('worker', models.ManyToManyField(blank=True, to='warehousemanager.Person')),
            ],
        ),
    ]
