# Generated by Django 3.1.2 on 2020-11-23 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehousemanager', '0032_auto_20201120_0505'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='name',
            field=models.CharField(blank=True, max_length=16),
        ),
    ]
