# Generated by Django 3.1.2 on 2020-11-28 18:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('warehousemanager', '0033_orderitem_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionProcess',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('KLSD', 'KLEJENIE-SKLEJARKA-DUŻA'), ('KLSM', 'KLEJENIE-SKLEJARKA-MAŁA'), ('KLR', 'KLEJENIE-RĘCZNE'), ('DR', 'DRUKOWANIE'), ('WY', 'WYCINANIE'), ('WY+DR', 'WYCINANIE Z NADRUKIEM'), ('SZ', 'SZTANCOWANIE'), ('OB', 'OBRYWANIE'), ('PK', 'PAKOWANIE'), ('INNE', 'INNE')], max_length=8)),
                ('date_start', models.DateField()),
                ('date_end', models.DateField()),
                ('machine', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='warehousemanager.machine')),
                ('stock', models.ManyToManyField(to='warehousemanager.OrderItemQuantity')),
                ('worker', models.ManyToManyField(blank=True, to='warehousemanager.Person')),
            ],
        ),
    ]
