# Generated by Django 3.1.2 on 2020-12-03 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehousemanager', '0036_auto_20201128_1930'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyer',
            name='shortcut',
            field=models.CharField(default='<djang', max_length=32),
        ),
    ]
