# Generated by Django 3.1.2 on 2020-12-03 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehousemanager', '0037_buyer_shortcut'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyer',
            name='shortcut',
            field=models.CharField(default=models.CharField(max_length=32), max_length=32),
        ),
    ]
