# Generated by Django 3.1.2 on 2020-12-10 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehousemanager', '0038_auto_20201203_2343'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='cardboard_additional_info',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='cardboard_type',
            field=models.CharField(choices=[('3B', '3B'), ('3C', '3C'), ('3E', '3E'), ('5BC', '5BC'), ('5EB', '5EB'), ('BB', 'BB'), ('BCS', 'BCS'), ('BS', 'BS')], max_length=8),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='sort',
            field=models.CharField(choices=[('201', 'FEFCO 201'), ('202', 'FEFCO 202'), ('203', 'FEFCO 203'), ('301', 'FEFCO 301'), ('SZTANCA', 'Sztanca'), ('PRZEKLADKA', 'Przekładka'), ('MAG', 'Magazyn'), ('ROT/TYG', 'Rotacja/Tygiel')], max_length=15),
        ),
        migrations.AlterField(
            model_name='punch',
            name='cardboard',
            field=models.CharField(choices=[('3B', '3B'), ('3C', '3C'), ('3E', '3E'), ('5BC', '5BC'), ('5EB', '5EB'), ('BB', 'BB'), ('BCS', 'BCS'), ('BS', 'BS')], max_length=4),
        ),
    ]
