# Generated by Django 3.1.2 on 2020-12-16 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehousemanager', '0040_auto_20201214_2011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyer',
            name='shortcut',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='machine',
            name='shortcut',
            field=models.CharField(max_length=16),
        ),
    ]
