# Generated by Django 3.1.2 on 2021-01-05 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehousemanager', '0041_auto_20201216_0600'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_date', models.DateField(auto_created=True)),
                ('date', models.DateField()),
                ('last_modification', models.DateField(auto_now=True)),
                ('description', models.TextField()),
                ('workers', models.ManyToManyField(to='warehousemanager.Person')),
            ],
        ),
    ]
