# Generated by Django 3.1.2 on 2021-01-08 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehousemanager', '0042_dailyreport'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderitem',
            options={'ordering': ['order__date_of_order', 'order__provider__name', 'order__order_provider_number', 'item_number']},
        ),
        migrations.AddField(
            model_name='orderitem',
            name='planned_delivery',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='sort',
            field=models.CharField(choices=[('201', 'FEFCO 201'), ('202', 'FEFCO 202'), ('203', 'FEFCO 203'), ('301', 'FEFCO 301'), ('409', 'FEFCO 409'), ('SZTANCA', 'Sztanca'), ('PRZEKLADKA', 'Przekładka'), ('MAG', 'Magazyn'), ('ROT/TYG', 'Rotacja/Tygiel')], max_length=15),
        ),
    ]
