# Generated by Django 3.1.2 on 2021-01-15 17:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('warehousemanager', '0043_auto_20210108_0434'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photopolymer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producer', models.CharField(choices=[('AMBR', 'AMBR'), ('CHESPA', 'CHESPA')], max_length=16)),
                ('identification_number', models.IntegerField()),
                ('delivery_date', models.DateField(blank=True, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='warehousemanager.buyer')),
            ],
        ),
        migrations.CreateModel(
            name='PhotopolymerService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('send_date', models.DateField()),
                ('service_description', models.CharField(max_length=200)),
                ('return_date', models.DateField(blank=True, null=True)),
                ('photopolymer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='warehousemanager.photopolymer')),
            ],
        ),
    ]
