# Generated by Django 3.1.2 on 2021-01-15 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehousemanager', '0044_photopolymer_photopolymerservice'),
    ]

    operations = [
        migrations.AddField(
            model_name='photopolymer',
            name='project',
            field=models.FileField(null=True, upload_to='pdf'),
        ),
    ]
