# Generated by Django 3.1.2 on 2021-01-18 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehousemanager', '0045_photopolymer_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='photopolymerservice',
            name='company',
            field=models.CharField(default='', max_length=16),
        ),
        migrations.AlterField(
            model_name='photopolymer',
            name='project',
            field=models.FileField(blank=True, null=True, upload_to='projects'),
        ),
    ]
