# Generated by Django 3.1.2 on 2021-01-26 02:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('warehousemanager', '0048_auto_20210120_1916'),
    ]

    operations = [
        migrations.AddField(
            model_name='productionprocess',
            name='polymer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='warehousemanager.photopolymer'),
        ),
        migrations.AlterField(
            model_name='photopolymerservice',
            name='photopolymer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehousemanager.photopolymer'),
        ),
        migrations.AlterField(
            model_name='productionprocess',
            name='date_end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='productionprocess',
            name='date_start',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='productionprocess',
            name='quantity_end',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='productionprocess',
            name='quantity_start',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='productionprocess',
            name='stock',
            field=models.ManyToManyField(blank=True, to='warehousemanager.OrderItemQuantity'),
        ),
        migrations.AlterField(
            model_name='punch',
            name='cardboard',
            field=models.CharField(choices=[('B', 'B'), ('C', 'C'), ('E', 'E'), ('BC', 'BC'), ('EB', 'EB')], max_length=4),
        ),
    ]
