# Generated by Django 3.1.2 on 2021-01-26 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehousemanager', '0051_auto_20210126_0427'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='color',
            name='company',
        ),
        migrations.AddField(
            model_name='colordelivery',
            name='company',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
