# Generated by Django 3.1.2 on 2021-01-26 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehousemanager', '0052_auto_20210126_0428'),
    ]

    operations = [
        migrations.AddField(
            model_name='color',
            name='availability',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
