# Generated by Django 3.1.2 on 2021-01-26 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehousemanager', '0053_color_availability'),
    ]

    operations = [
        migrations.AddField(
            model_name='color',
            name='blue',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='color',
            name='green',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='color',
            name='red',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
