# Generated by Django 3.1.2 on 2021-01-27 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehousemanager', '0055_auto_20210127_0535'),
    ]

    operations = [
        migrations.AddField(
            model_name='productionprocess',
            name='note',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
