# Generated by Django 3.1.2 on 2021-01-27 18:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('warehousemanager', '0056_productionprocess_note'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='color',
            options={'ordering': ['name']},
        ),
        migrations.RemoveField(
            model_name='productionprocess',
            name='colors',
        ),
        migrations.AddField(
            model_name='colorusage',
            name='production',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='warehousemanager.productionprocess'),
        ),
    ]
