# Generated by Django 3.1.2 on 2021-01-27 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehousemanager', '0057_auto_20210127_1930'),
    ]

    operations = [
        migrations.AddField(
            model_name='colordelivery',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
