# Generated by Django 3.1.2 on 2021-01-29 19:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('warehousemanager', '0058_colordelivery_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='ColorSpecialEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(max_length=32)),
                ('date', models.DateField()),
                ('difference', models.DecimalField(decimal_places=1, max_digits=4)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehousemanager.color')),
            ],
        ),
    ]
