# Generated by Django 3.1.2 on 2021-02-03 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehousemanager', '0059_colorspecialevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='extrahour',
            name='full_day',
            field=models.BooleanField(default=True),
        ),
    ]
