# Generated by Django 3.1.2 on 2021-02-04 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehousemanager', '0061_auto_20210203_2232'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='amount_2021',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
