# Generated by Django 3.1.2 on 2021-02-05 04:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('warehousemanager', '0062_person_amount_2021'),
    ]

    operations = [
        migrations.CreateModel(
            name='Palette',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('width', models.PositiveIntegerField(default=1200)),
                ('height', models.PositiveIntegerField(default=800)),
                ('type', models.CharField(choices=[('EU', 'Euro'), ('OR', 'Ordinary')], max_length=4)),
            ],
        ),
        migrations.AlterField(
            model_name='orderitemquantity',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='PaletteQuantity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('status', models.CharField(choices=[('DEL', 'Delivered'), ('RET', 'returned')], max_length=4)),
                ('delivery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehousemanager.delivery')),
                ('palette', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehousemanager.palette')),
            ],
        ),
        migrations.AddField(
            model_name='delivery',
            name='palettes',
            field=models.ManyToManyField(through='warehousemanager.PaletteQuantity', to='warehousemanager.Palette'),
        ),
    ]
