# Generated by Django 3.1.2 on 2021-02-09 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehousemanager', '0063_auto_20210205_0542'),
    ]

    operations = [
        migrations.AddField(
            model_name='absence',
            name='value',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True),
        ),
        migrations.AlterField(
            model_name='palettequantity',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='palettequantity',
            name='status',
            field=models.CharField(choices=[('DEL', 'Delivered'), ('RET', 'returned')], default='DEL', max_length=4),
        ),
    ]
