# Generated by Django 3.1.2 on 2021-02-09 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehousemanager', '0064_auto_20210209_0510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='absence',
            name='value',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
