# Generated by Django 3.1.2 on 2021-02-18 03:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warehousemanager', '0065_auto_20210209_0519'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='amount_2021',
            new_name='amount_2020',
        ),
    ]
