# Generated by Django 3.1.2 on 2021-02-25 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warehousemanager', '0066_auto_20210218_0430'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserVisitCounter',
        ),
    ]
