# Generated by Django 3.1.2 on 2021-02-25 18:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('warehousemanager', '0067_delete_uservisitcounter'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserVisitCounter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.CharField(max_length=32)),
                ('counter', models.PositiveIntegerField(default=0)),
                ('first_visit', models.DateTimeField(blank=True, null=True)),
                ('last_visit', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
