# Generated by Django 3.1.2 on 2021-03-05 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehousemanager', '0069_contract'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='salary',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
    ]
