# Generated by Django 3.1.2 on 2021-03-06 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehousemanager', '0072_contract_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='medical_examination',
            field=models.DateField(blank=True, null=True),
        ),
    ]
