# Generated by Django 3.1.7 on 2021-04-07 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehousemanager', '0074_reminder'),
    ]

    operations = [
        migrations.AddField(
            model_name='absence',
            name='additional_info',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='absence',
            name='absence_type',
            field=models.CharField(choices=[('NN', 'Nieobecność nieusprawiedliwiona'), ('UW', 'Urlop wypoczynkowy'), ('UO', 'Urlop okolicznościowy'), ('SP', 'Spóźnienie'), ('UB', 'Urlop bezpłatny'), ('CH', 'Chorobowe'), ('KW', 'Kwarantanna'), ('OP', 'Opieka nad członkiem rodziny'), ('D', 'Delegacja'), ('IN', 'Inne')], max_length=4),
        ),
    ]
