# Generated by Django 3.1.7 on 2021-04-08 03:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('warehousemanager', '0076_person_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaletteCustomer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('extra_info', models.CharField(blank=True, max_length=255, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehousemanager.buyer')),
                ('palette', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='warehousemanager.palette')),
            ],
        ),
    ]
