# Generated by Django 3.1.7 on 2021-04-08 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehousemanager', '0077_palettecustomer'),
    ]

    operations = [
        migrations.AddField(
            model_name='palettecustomer',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
