# Generated by Django 3.1.7 on 2021-04-08 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehousemanager', '0078_palettecustomer_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='palettecustomer',
            name='status',
            field=models.CharField(choices=[('DEL', 'Delivered'), ('RET', 'returned')], default='DEL', max_length=4),
        ),
    ]
