# Generated by Django 3.1.7 on 2021-04-12 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warehousemanager', '0081_auto_20210412_1931'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='date_send',
            new_name='date_sent',
        ),
    ]
