# Generated by Django 3.1.7 on 2021-05-20 19:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('warehousemanager', '0083_auto_20210415_1152'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cloth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('description', models.CharField(max_length=512)),
            ],
        ),
        migrations.AlterModelOptions(
            name='uservisitcounter',
            options={'ordering': ['-last_visit']},
        ),
        migrations.CreateModel(
            name='WorkerWorkWear',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('cloth', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehousemanager.cloth')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehousemanager.person')),
            ],
        ),
    ]
