# Generated by Django 3.1.7 on 2021-05-20 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehousemanager', '0084_auto_20210520_2133'),
    ]

    operations = [
        migrations.AddField(
            model_name='workerworkwear',
            name='number_or_size',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='cloth',
            name='description',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
