# Generated by Django 3.2.4 on 2021-06-06 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warehousemanager', '0085_auto_20210520_2143'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='holiday',
            options={'ordering': ['-holiday_date']},
        ),
        migrations.AlterModelOptions(
            name='workerworkwear',
            options={'ordering': ['-date']},
        ),
    ]
