# Generated by Django 3.2.4 on 2021-06-09 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehousemanager', '0086_auto_20210606_1213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uservisitcounter',
            name='page',
            field=models.CharField(max_length=64),
        ),
    ]
