# Generated by Django 3.2.4 on 2021-10-15 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehousemanager', '0087_alter_uservisitcounter_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='occupancy_type',
            field=models.CharField(default='PRODUCTION', max_length=32),
        ),
    ]
