# Generated by Django 3.2.9 on 2022-06-21 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehousemanager', '0089_auto_20220202_1442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='absence',
            name='absence_type',
            field=models.CharField(choices=[('NN', 'Nieobecność nieusprawiedliwiona'), ('UW', 'Urlop wypoczynkowy'), ('UŻ', 'Urlop na żądanie'), ('UO', 'Urlop okolicznościowy'), ('SP', 'Spóźnienie'), ('UB', 'Urlop bezpłatny'), ('CH', 'Chorobowe'), ('KW', 'Kwarantanna'), ('OP', 'Opieka nad członkiem rodziny'), ('D', 'Delegacja'), ('IN', 'Inne'), ('IZ', 'Izolacja'), ('PO', 'Postojowe')], max_length=4),
        ),
    ]
