# Generated by Django 3.1.3 on 2023-06-15 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warehousemanager', '0090_alter_absence_absence_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='photopolymer',
            options={'ordering': ['identification_number']},
        ),
        migrations.AlterModelOptions(
            name='punch',
            options={'ordering': ['type', 'type_letter', 'type_num']},
        ),
    ]
