# Generated by Django 3.1.3 on 2023-09-20 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehousemanager', '0091_auto_20230615_1909'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkReminder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Reminder', max_length=64)),
                ('add_date', models.DateTimeField(auto_now_add=True)),
                ('content', models.TextField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('alert_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='punch',
            name='type',
            field=models.CharField(choices=[('471', 'FEFCO 471'), ('427', 'FEFCO 427'), ('426', 'FEFCO 426'), ('421', 'FEFCO 421'), ('201', 'FEFCO 201'), ('SWT', 'Spody, wieka, tacki'), ('KR', 'Krata'), ('NR', 'Narożnik'), ('PDK', 'Pozostałe do klejenia'), ('WK', 'Wkład'), ('INNE', 'Inne')], max_length=8),
        ),
    ]
