# Generated by Django 5.0.1 on 2024-03-01 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehousemanager', '0093_alter_contract_options_alter_contract_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photopolymer',
            name='name',
            field=models.CharField(default='', max_length=128),
        ),
    ]
