# Generated by Django 5.0.1 on 2024-04-30 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehousemanager', '0094_alter_photopolymer_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='punch',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
