# Generated by Django 5.0.1 on 2024-06-26 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehousemanager', '0096_gluernumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='photopolymer',
            name='dimensions',
            field=models.CharField(blank='', default='', max_length=32),
        ),
    ]
