# Generated by Django 5.0.1 on 2024-07-05 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehousemanager', '0098_alter_photopolymer_identification_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='photopolymer',
            name='identification_letter',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='photopolymer',
            name='identification_number',
            field=models.IntegerField(),
        ),
    ]
