# Generated by Django 5.0.1 on 2024-07-05 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehousemanager', '0099_photopolymer_identification_letter_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='photopolymer',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='photopolymer',
            name='dimensions',
            field=models.CharField(blank='', max_length=32, null=True),
        ),
    ]
