# Generated by Django 5.0.1 on 2024-07-05 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehousemanager', '0100_photopolymer_active_alter_photopolymer_dimensions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photopolymer',
            name='dimensions',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
