# Generated by Django 5.0.1 on 2024-07-25 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehousemanager', '0101_alter_photopolymer_dimensions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='punch',
            name='name',
            field=models.CharField(blank=True, default='', max_length=96),
        ),
    ]
