# Generated by Django 5.0.1 on 2024-07-25 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehousemanager', '0103_person_date26'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='first',
            field=models.BooleanField(default=False),
        ),
    ]
