# Generated by Django 5.0.1 on 2024-08-01 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehousemanager', '0104_contract_first'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='date26',
        ),
        migrations.AlterField(
            model_name='person',
            name='occupancy_type',
            field=models.CharField(choices=[('MECHANIC', 'MECHANIC'), ('PRODUCTION', 'PRODUCTION'), ('OFFICE', 'OFFICE'), ('OTHER', 'OTHER'), ('MANAGEMENT', 'MANAGEMENT'), ('LOGISTIC', 'LOGISTIC')], default='PRODUCTION', max_length=32),
        ),
    ]
