# Generated by Django 5.0.1 on 2024-10-14 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehousemanager', '0105_remove_person_date26_alter_person_occupancy_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gluernumber',
            name='comments',
            field=models.TextField(blank=True, null=True),
        ),
    ]
