# Generated by Django 5.0.1 on 2024-11-08 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warehousemanager', '0107_alter_gluernumber_dimensions_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gluernumber',
            options={'ordering': ('number',)},
        ),
    ]
