# Generated by Django 5.0.1 on 2025-03-27 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warehousemanager', '0108_alter_gluernumber_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='colorspecialevent',
            name='color',
        ),
        migrations.DeleteModel(
            name='ColorDelivery',
        ),
        migrations.DeleteModel(
            name='ColorSpecialEvent',
        ),
    ]
