# Generated by Django 5.0.1 on 2025-03-28 08:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehousemanager', '0109_remove_colorspecialevent_color_delete_colordelivery_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ColorBucket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('INERGIS', 'INERGIS'), ('NEOINK', 'NEOINK'), ('AQUA POLIMERY', 'AQUA POLIMERY'), ('CHESPA', 'CHESPA')], max_length=32)),
                ('weight', models.DecimalField(decimal_places=1, max_digits=3)),
                ('production_date', models.DateField(blank=True, null=True)),
                ('expiration_date', models.DateField(blank=True, null=True)),
                ('usage', models.TextField(blank=True, null=True)),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='warehousemanager.color')),
            ],
        ),
    ]
