# Generated by Django 5.0.1 on 2025-06-27 11:34

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0020_productionunit_required_helpers_and_more'),
        ('warehousemanager', '0111_photopolymer_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkStationQualification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acquired_at', models.DateField(default=django.utils.timezone.now)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehousemanager.person')),
                ('workstation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production.workstation')),
            ],
            options={
                'unique_together': {('person', 'workstation')},
            },
        ),
        migrations.AddField(
            model_name='person',
            name='qualified_workstations',
            field=models.ManyToManyField(blank=True, related_name='qualified_persons', through='warehousemanager.WorkStationQualification', to='production.workstation'),
        ),
    ]
