# Generated by Django 5.0.1 on 2025-07-02 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warehousemanager', '0112_workstationqualification_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='photopolymer',
            options={'ordering': ['identification_number', 'identification_letter']},
        ),
    ]
