# Generated by Django 5.0.1 on 2025-07-23 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehousemanager', '0113_alter_photopolymer_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocalSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('value', models.CharField(max_length=128)),
            ],
        ),
    ]
