# Generated by Django 5.0.1 on 2025-09-05 13:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehousemanager', '0114_localsetting'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyer',
            name='tax_number',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.CreateModel(
            name='CustomerDeliveryPlace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Main', max_length=32)),
                ('latitude', models.CharField(max_length=16)),
                ('longitude', models.CharField(max_length=16)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='warehousemanager.buyer')),
            ],
            options={
                'ordering': ['customer__name'],
            },
        ),
    ]
