# Generated by Django 5.0.1 on 2025-09-08 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehousemanager', '0115_buyer_tax_number_customerdeliveryplace'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerdeliveryplace',
            name='lat_long',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='customerdeliveryplace',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customerdeliveryplace',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
