# Generated by Django 5.0.1 on 2025-09-08 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehousemanager', '0116_customerdeliveryplace_lat_long_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerdeliveryplace',
            name='delivery_frequency',
            field=models.CharField(choices=[('rare', 'Rare'), ('occasional', 'Occasional'), ('regular', 'Regular'), ('frequent', 'Frequent')], default='occasional', max_length=16),
        ),
    ]
