# Generated by Django 5.0.1 on 2026-05-13 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehousemanager', '0118_person_birth_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='occupancy_type',
            field=models.CharField(choices=[('MECHANIC', 'MECHANIC'), ('PRODUCTION', 'PRODUCTION'), ('OFFICE', 'OFFICE'), ('OTHER', 'OTHER'), ('MANAGEMENT', 'MANAGEMENT'), ('LOGISTIC', 'LOGISTIC'), ('MAN/PROD', 'MAN/PROD')], default='PRODUCTION', max_length=32),
        ),
    ]
