# Generated by Django 5.0.1 on 2026-07-23 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehousemanager', '0119_alter_person_occupancy_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='pin',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
    ]
