# Generated by Django 5.0.1 on 2026-09-16 14:11

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehousemanager', '0120_person_pin'),
    ]

    operations = [
        migrations.CreateModel(
            name='ColorOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('INERGIS', 'INERGIS'), ('NEOINK', 'NEOINK'), ('AQUA POLIMERY', 'AQUA POLIMERY'), ('CHESPA', 'CHESPA'), ('CHEMTEX', 'CHEMTEX')], max_length=32)),
                ('order_date', models.DateField(default=django.utils.timezone.localdate)),
                ('received_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('open', 'Zamówione'), ('received', 'Przyjęte'), ('cancelled', 'Anulowane')], default='open', max_length=16)),
                ('number', models.CharField(blank=True, max_length=64, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-order_date', '-id'],
            },
        ),
        migrations.AlterField(
            model_name='colorbucket',
            name='provider',
            field=models.CharField(choices=[('INERGIS', 'INERGIS'), ('NEOINK', 'NEOINK'), ('AQUA POLIMERY', 'AQUA POLIMERY'), ('CHESPA', 'CHESPA'), ('CHEMTEX', 'CHEMTEX')], max_length=32),
        ),
        migrations.CreateModel(
            name='ColorOrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_kg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price_per_kg', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='warehousemanager.color')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='warehousemanager.colororder')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='colorbucket',
            name='order_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='buckets', to='warehousemanager.colororderitem'),
        ),
    ]
