# Generated by Django 5.0.1 on 2026-09-16 15:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehousemanager', '0121_colororder_alter_colorbucket_provider_colororderitem_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colororder',
            name='order_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
