# Generated by Django 5.0.1 on 2026-09-16 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehousemanager', '0122_alter_colororder_order_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photopolymer',
            name='identification_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
