# Generated by Django 5.0.1 on 2024-11-26 10:56

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('warehousemanager', '0108_alter_gluernumber_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=64, unique=True)),
                ('date', models.DateField()),
                ('car_number', models.CharField(blank=True, max_length=16, null=True)),
                ('telephone', models.CharField(blank=True, max_length=16, null=True)),
                ('description', models.CharField(blank=True, max_length=256, null=True)),
                ('processed', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Palette',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('shortcut', models.CharField(blank=True, max_length=24, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='StockType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_type', models.CharField(max_length=64)),
                ('unit', models.CharField(choices=[('KG', 'KG'), ('M2', 'M2'), ('PIECE', 'PIECE'), ('SET', 'SET')], max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=32)),
                ('customer_date', models.DateField()),
                ('order_date', models.DateField(blank=True, null=True)),
                ('order_year', models.CharField(blank=True, max_length=4, null=True)),
                ('delivery_date', models.DateField(blank=True, null=True)),
                ('production_date', models.DateField(blank=True, null=True)),
                ('dimensions', models.CharField(max_length=32)),
                ('name', models.CharField(max_length=32)),
                ('weight', models.PositiveIntegerField(default=0)),
                ('order_quantity', models.PositiveIntegerField()),
                ('delivered_quantity', models.PositiveIntegerField(default=0)),
                ('price', models.PositiveIntegerField(default=0)),
                ('delivered', models.BooleanField(default=False)),
                ('finished', models.BooleanField(default=False)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='warehousemanager.buyer')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='warehouse.product')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='warehouse.provider')),
            ],
            options={
                'ordering': ['order_date', 'provider', 'order_id'],
                'unique_together': {('provider', 'order_id', 'order_year')},
            },
        ),
        migrations.CreateModel(
            name='DeliveryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('palettes_quantity', models.CharField(blank=True, max_length=128, null=True)),
                ('processed', models.BooleanField(default=False)),
                ('delivery', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='warehouse.delivery')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='warehouse.order')),
            ],
        ),
        migrations.CreateModel(
            name='OrderSettlement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_quantity', models.PositiveIntegerField(default=0)),
                ('settlement_date', models.DateField(default=datetime.date.today)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='settlements', to='warehouse.order')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='used_in_settlements', to='warehouse.stock')),
            ],
        ),
        migrations.CreateModel(
            name='DeliveryPalette',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('delivery', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='warehouse.delivery')),
                ('palette', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='warehouse.palette')),
            ],
        ),
        migrations.AddField(
            model_name='delivery',
            name='palettes',
            field=models.ManyToManyField(blank=True, through='warehouse.DeliveryPalette', to='warehouse.palette'),
        ),
        migrations.AddField(
            model_name='delivery',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='warehouse.provider'),
        ),
        migrations.CreateModel(
            name='StockSupply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dimensions', models.CharField(blank=True, max_length=32, null=True)),
                ('weight', models.PositiveIntegerField(blank=True, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('name', models.CharField(max_length=64)),
                ('delivery_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='warehouse.deliveryitem')),
                ('stock_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='warehouse.stocktype')),
            ],
        ),
        migrations.CreateModel(
            name='OrderSettlementProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('is_semi_product', models.BooleanField(default=False)),
                ('settlement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='settlement_products', to='warehouse.ordersettlement')),
                ('stock_supply', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='warehouse.stocksupply')),
            ],
        ),
        migrations.AddField(
            model_name='stock',
            name='stock_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='warehouse.stocktype'),
        ),
        migrations.CreateModel(
            name='WarehouseStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warehouse_stocks', to='warehouse.stock')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warehouse_stocks', to='warehouse.warehouse')),
            ],
        ),
    ]
