# Generated by Django 5.0.1 on 2024-11-08 08:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('shortcut', models.CharField(blank=True, max_length=24, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='StockType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_type', models.CharField(max_length=64)),
                ('unit', models.CharField(choices=[('KG', 'KG'), ('M2', 'M2'), ('PIECE', 'PIECE'), ('SET', 'SET')], max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='StockSupply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('name', models.CharField(max_length=64)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='warehouse.provider')),
                ('stock_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='warehouse.stocktype')),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('name', models.CharField(max_length=64)),
                ('supplies', models.ManyToManyField(to='warehouse.stocksupply')),
                ('stock_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='warehouse.stocktype')),
            ],
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('stocks', models.ManyToManyField(to='warehouse.stock')),
            ],
        ),
    ]
