# Generated by Django 5.0.1 on 2024-11-26 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stocksupply',
            name='weight',
        ),
    ]
