# Generated by Django 5.0.1 on 2025-06-09 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0002_warehouse_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='updated',
            field=models.BooleanField(default=False),
        ),
    ]
