# Generated by Django 5.0.1 on 2024-11-08 11:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0002_stocksupply_dimensions_stocksupply_weight_and_more'),
        ('warehousemanager', '0108_alter_gluernumber_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Palette',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('car_number', models.CharField(blank=True, max_length=16, null=True)),
                ('telephone', models.CharField(blank=True, max_length=16, null=True)),
                ('description', models.CharField(blank=True, max_length=256, null=True)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='warehouse.provider')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=32)),
                ('customer_date', models.DateField()),
                ('order_date', models.DateField(blank=True, null=True)),
                ('delivery_date', models.DateField(blank=True, null=True)),
                ('production_date', models.DateField(blank=True, null=True)),
                ('dimensions', models.CharField(max_length=32)),
                ('name', models.CharField(max_length=32)),
                ('weight', models.PositiveIntegerField(default=0)),
                ('order_quantity', models.PositiveIntegerField()),
                ('delivered_quantity', models.PositiveIntegerField(default=0)),
                ('price', models.PositiveIntegerField(default=0)),
                ('delivered', models.BooleanField(default=False)),
                ('finished', models.BooleanField(default=False)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='warehousemanager.buyer')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='warehouse.provider')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='warehouse.product')),
            ],
        ),
        migrations.CreateModel(
            name='DeliveryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('delivery', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='warehouse.delivery')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='warehouse.order')),
            ],
        ),
        migrations.CreateModel(
            name='DeliveryPalette',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('delivery', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='warehouse.delivery')),
                ('palette', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='warehouse.palette')),
            ],
        ),
        migrations.AddField(
            model_name='delivery',
            name='palettes',
            field=models.ManyToManyField(through='warehouse.DeliveryPalette', to='warehouse.palette'),
        ),
    ]
