# Generated by Django 5.0.1 on 2025-06-09 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0003_order_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='updated',
            field=models.BooleanField(default=False),
        ),
    ]
