# Generated by Django 5.0.1 on 2024-11-08 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0003_palette_product_delivery_order_deliveryitem_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.CharField(max_length=32, unique=True),
        ),
    ]
