# Generated by Django 5.0.1 on 2024-11-10 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0003_palette_product_delivery_order_deliveryitem_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['order_date', 'provider', 'order_id']},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['name']},
        ),
        migrations.AlterField(
            model_name='delivery',
            name='palettes',
            field=models.ManyToManyField(blank=True, through='warehouse.DeliveryPalette', to='warehouse.palette'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='supplies',
            field=models.ManyToManyField(blank=True, to='warehouse.stocksupply'),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='stocks',
            field=models.ManyToManyField(blank=True, to='warehouse.stock'),
        ),
    ]
