# Generated by Django 5.0.1 on 2024-11-10 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0004_alter_order_options_alter_product_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliveryitem',
            name='delivery',
        ),
        migrations.RemoveField(
            model_name='deliverypalette',
            name='delivery',
        ),
        migrations.RemoveField(
            model_name='deliveryitem',
            name='order',
        ),
        migrations.RemoveField(
            model_name='deliverypalette',
            name='palette',
        ),
        migrations.RemoveField(
            model_name='order',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='order',
            name='product',
        ),
        migrations.RemoveField(
            model_name='order',
            name='provider',
        ),
        migrations.RemoveField(
            model_name='stocksupply',
            name='provider',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='stock_type',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='supplies',
        ),
        migrations.RemoveField(
            model_name='warehouse',
            name='stocks',
        ),
        migrations.RemoveField(
            model_name='stocksupply',
            name='stock_type',
        ),
        migrations.DeleteModel(
            name='Delivery',
        ),
        migrations.DeleteModel(
            name='DeliveryItem',
        ),
        migrations.DeleteModel(
            name='DeliveryPalette',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='Provider',
        ),
        migrations.DeleteModel(
            name='Stock',
        ),
        migrations.DeleteModel(
            name='Warehouse',
        ),
        migrations.DeleteModel(
            name='StockSupply',
        ),
        migrations.DeleteModel(
            name='StockType',
        ),
    ]
