# Generated by Django 5.0.1 on 2024-11-10 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0004_alter_order_order_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['provider', 'order_id']},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='deliveryitem',
            name='palettes_quantity',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='palettes',
            field=models.ManyToManyField(null=True, through='warehouse.DeliveryPalette', to='warehouse.palette'),
        ),
    ]
