# Generated by Django 5.0.1 on 2024-11-12 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0004_alter_order_options_alter_product_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryitem',
            name='palettes_quantity',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
