# Generated by Django 5.0.1 on 2025-06-25 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0005_productsell'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='warehousestock',
            options={'ordering': ['stock__name']},
        ),
        migrations.AlterField(
            model_name='deliveryitem',
            name='palettes_quantity',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
