# Generated by Django 5.0.1 on 2024-11-12 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0005_deliveryitem_palettes_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_year',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='order',
            unique_together={('provider', 'order_id', 'order_year')},
        ),
    ]
