# Generated by Django 5.0.1 on 2024-11-10 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0005_alter_order_options_alter_product_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['order_date', 'provider', 'order_id']},
        ),
        migrations.AlterUniqueTogether(
            name='order',
            unique_together={('order_id', 'provider')},
        ),
    ]
