# Generated by Django 5.0.1 on 2024-11-10 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0006_alter_order_options_alter_order_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='order',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='palettes',
            field=models.ManyToManyField(blank=True, through='warehouse.DeliveryPalette', to='warehouse.palette'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='stock',
            name='supplies',
            field=models.ManyToManyField(blank=True, to='warehouse.stocksupply'),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='stocks',
            field=models.ManyToManyField(blank=True, to='warehouse.stock'),
        ),
    ]
