# Generated by Django 5.0.1 on 2024-11-12 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0006_order_order_year_alter_order_unique_together'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DeliveryItem',
        ),
    ]
