# Generated by Django 5.0.1 on 2025-07-03 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0006_alter_warehousestock_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthResults',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.PositiveIntegerField()),
                ('year', models.PositiveIntegerField()),
                ('expenses', models.PositiveIntegerField()),
                ('management_expenses', models.PositiveIntegerField()),
            ],
        ),
    ]
