# Generated by Django 5.0.1 on 2025-07-03 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0007_monthresults'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthresults',
            name='financial_expenses',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='monthresults',
            name='logistic_expenses',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='monthresults',
            name='other_expenses',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
