# Generated by Django 5.0.1 on 2025-07-21 11:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0009_productsell2'),
        ('warehousemanager', '0113_alter_photopolymer_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('description', models.CharField(blank=True, max_length=256, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='warehousemanager.buyer')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='DeliveryCustomerPalette',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('customer_delivery', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='warehouse.customerdelivery')),
                ('palette', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='warehouse.palette')),
            ],
        ),
        migrations.AddField(
            model_name='customerdelivery',
            name='palettes',
            field=models.ManyToManyField(blank=True, through='warehouse.DeliveryCustomerPalette', to='warehouse.palette'),
        ),
        migrations.CreateModel(
            name='DeliverySell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_delivery', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='warehouse.customerdelivery')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='warehouse.productsell2')),
            ],
        ),
        migrations.AddField(
            model_name='customerdelivery',
            name='items',
            field=models.ManyToManyField(blank=True, through='warehouse.DeliverySell', to='warehouse.productsell2'),
        ),
    ]
