# Generated by Django 5.0.1 on 2024-11-13 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0009_delivery_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='number',
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
