# Generated by Django 5.0.1 on 2024-11-14 14:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0010_alter_delivery_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='delivery',
            options={'ordering': ['-date']},
        ),
        migrations.RemoveField(
            model_name='stocksupply',
            name='provider',
        ),
        migrations.AddField(
            model_name='delivery',
            name='processed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='deliveryitem',
            name='processed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='stocksupply',
            name='delivery_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='warehouse.deliveryitem'),
        ),
    ]
