# Generated by Django 5.0.1 on 2025-07-22 12:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0010_customerdelivery_deliverycustomerpalette_and_more'),
        ('warehousemanager', '0113_alter_photopolymer_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerPalette',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='warehousemanager.buyer')),
                ('palette', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='warehouse.palette')),
            ],
            options={
                'ordering': ['customer'],
                'unique_together': {('customer', 'palette')},
            },
        ),
    ]
