# Generated by Django 5.0.1 on 2024-11-15 14:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0011_alter_delivery_options_remove_stocksupply_provider_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='supplies',
        ),
        migrations.RemoveField(
            model_name='warehouse',
            name='stocks',
        ),
        migrations.CreateModel(
            name='WarehouseStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warehouse_stocks', to='warehouse.stock')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warehouse_stocks', to='warehouse.warehouse')),
            ],
        ),
    ]
