# Generated by Django 5.0.1 on 2025-07-23 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0011_customerpalette'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerpalette',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='deliverycustomerpalette',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
