# Generated by Django 5.0.1 on 2024-11-16 08:48

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0012_remove_stock_supplies_remove_warehouse_stocks_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderSettlement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_quantity', models.PositiveIntegerField(default=0)),
                ('settlement_date', models.DateField(default=datetime.date.today)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='used_in_settlements', to='warehouse.stock')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='settlements', to='warehouse.order')),
            ],
        ),
        migrations.CreateModel(
            name='OrderSettlementProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('is_semi_product', models.BooleanField(default=False)),
                ('settlement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='settlement_products', to='warehouse.ordersettlement')),
                ('stock_supply', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='warehouse.stocksupply')),
            ],
        ),
    ]
