# Generated by Django 5.0.1 on 2024-11-22 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0013_ordersettlement_ordersettlementproduct'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrderSettlement',
        ),
        migrations.DeleteModel(
            name='OrderSettlementProduct',
        ),
        migrations.DeleteModel(
            name='Stock',
        ),
    ]
