# Generated by Django 5.0.1 on 2025-07-23 15:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0013_productsell3'),
    ]

    operations = [
        migrations.AddField(
            model_name='productsell3',
            name='warehouse_stock',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='warehouse.warehousestock'),
        ),
    ]
