# Generated by Django 5.0.1 on 2025-08-08 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0014_productsell3_warehouse_stock'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='delivery',
            options={'ordering': ['-date', 'id']},
        ),
    ]
