# Generated by Django 5.0.1 on 2025-08-08 10:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0015_alter_delivery_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductComplexAssembly',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('quantity', models.IntegerField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='warehouse.product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductComplexParts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('assembly', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='warehouse.productcomplexassembly')),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='warehouse.warehousestock')),
            ],
        ),
        migrations.AddField(
            model_name='productcomplexassembly',
            name='parts',
            field=models.ManyToManyField(blank=True, through='warehouse.ProductComplexParts', to='warehouse.warehousestock'),
        ),
    ]
