# Generated by Django 5.0.1 on 2025-08-08 13:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0016_productcomplexassembly_productcomplexparts_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehousestockhistory',
            name='assembly',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='warehouse.productcomplexassembly'),
        ),
    ]
