# Generated by Django 5.0.1 on 2025-08-14 06:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0017_warehousestockhistory_assembly'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliverySpecial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('provider', models.CharField(max_length=64)),
                ('date', models.DateField()),
                ('description', models.CharField(blank=True, max_length=256, null=True)),
                ('processed', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-date', 'id'],
            },
        ),
        migrations.AlterModelOptions(
            name='productcomplexassembly',
            options={'ordering': ['date', 'product']},
        ),
        migrations.AlterModelOptions(
            name='productcomplexparts',
            options={'ordering': ['assembly', 'part']},
        ),
        migrations.AlterField(
            model_name='productcomplexparts',
            name='assembly',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assembly_parts', to='warehouse.productcomplexassembly'),
        ),
        migrations.CreateModel(
            name='DeliverySpecialItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField()),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('processed', models.BooleanField(default=False)),
                ('delivery', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='warehouse.deliveryspecial')),
            ],
        ),
    ]
