# Generated by Django 5.0.1 on 2025-09-05 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0018_deliveryspecial_alter_productcomplexassembly_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productsell3',
            options={'ordering': ['date', '-customer', '-product']},
        ),
    ]
