# Generated by Django 5.0.1 on 2025-08-14 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0018_deliveryspecial_alter_productcomplexassembly_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryspecialitem',
            name='name',
            field=models.CharField(max_length=64),
        ),
    ]
