# Generated by Django 5.0.1 on 2025-09-11 10:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0019_alter_productsell3_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderToOrderShift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('order_from', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shifts_from', to='warehouse.order')),
                ('order_to', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shifts_to', to='warehouse.order')),
            ],
        ),
    ]
