# Generated by Django 5.0.1 on 2025-09-11 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0020_ordertoordershift'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='default_pieces',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=5),
        ),
    ]
