# Generated by Django 5.0.1 on 2025-09-12 11:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0021_order_default_pieces'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordertoordershift',
            name='date',
            field=models.DateField(default=datetime.date(2025, 9, 12)),
        ),
    ]
