# Generated by Django 5.0.1 on 2025-09-12 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0022_ordertoordershift_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordertoordershift',
            name='date',
            field=models.DateField(),
        ),
    ]
