# Generated by Django 5.0.1 on 2025-09-16 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0023_alter_ordertoordershift_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='productsell3',
            name='customer_alter_name',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
