# Generated by Django 5.0.1 on 2025-09-24 10:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0024_productsell3_customer_alter_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productsell3',
            options={'ordering': ['-date', '-customer', '-product']},
        ),
        migrations.AlterModelOptions(
            name='warehousestockhistory',
            options={'ordering': ['-date', '-warehouse_stock']},
        ),
        migrations.CreateModel(
            name='PriceList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_start', models.DateField()),
                ('date_end', models.DateField(blank=True, null=True)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='warehouse.provider')),
            ],
        ),
        migrations.CreateModel(
            name='PriceListItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16)),
                ('flute', models.CharField(max_length=4)),
                ('weight', models.IntegerField(default=0)),
                ('etc', models.DecimalField(decimal_places=2, max_digits=4)),
                ('price', models.IntegerField()),
                ('price2', models.IntegerField(blank=True, null=True)),
                ('price_list', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='warehouse.pricelist')),
            ],
            options={
                'unique_together': {('price_list', 'name')},
            },
        ),
    ]
