# Generated by Django 5.0.1 on 2025-09-24 10:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0025_alter_productsell3_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricelistitem',
            name='etc',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='pricelistitem',
            name='price_list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse.pricelist'),
        ),
    ]
