# Generated by Django 5.0.1 on 2025-09-24 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0026_alter_pricelistitem_etc_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='pricelist',
            unique_together={('provider', 'date_start')},
        ),
    ]
