# Generated by Django 5.0.1 on 2025-12-15 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0027_alter_pricelist_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryitem',
            name='updated',
            field=models.BooleanField(default=False),
        ),
    ]
