# Generated by Django 5.0.1 on 2025-12-16 09:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0028_deliveryitem_updated'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillOfMaterials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='BOMParts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('bom', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bom_parts', to='warehouse.billofmaterials')),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='warehouse.warehousestock')),
            ],
            options={
                'ordering': ['bom', 'part'],
            },
        ),
        migrations.AddField(
            model_name='billofmaterials',
            name='parts',
            field=models.ManyToManyField(blank=True, through='warehouse.BOMParts', to='warehouse.warehousestock'),
        ),
    ]
