# Generated by Django 5.0.1 on 2026-01-07 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0028_deliveryitem_updated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliverycustomerpalette',
            name='customer_delivery',
        ),
        migrations.RemoveField(
            model_name='deliverysell',
            name='customer_delivery',
        ),
        migrations.RemoveField(
            model_name='deliverycustomerpalette',
            name='palette',
        ),
        migrations.RemoveField(
            model_name='deliverysell',
            name='item',
        ),
        migrations.RemoveField(
            model_name='productsell',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='productsell',
            name='warehouse_stock',
        ),
        migrations.RemoveField(
            model_name='productsell2',
            name='order',
        ),
        migrations.RemoveField(
            model_name='productsell2',
            name='product',
        ),
        migrations.AddField(
            model_name='stocksupply',
            name='used',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='stocksupply',
            name='value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
        migrations.DeleteModel(
            name='CustomerDelivery',
        ),
        migrations.DeleteModel(
            name='DeliveryCustomerPalette',
        ),
        migrations.DeleteModel(
            name='DeliverySell',
        ),
        migrations.DeleteModel(
            name='ProductSell',
        ),
        migrations.DeleteModel(
            name='ProductSell2',
        ),
    ]
