# Generated by Django 5.0.1 on 2025-12-16 10:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0029_billofmaterials_bomparts_billofmaterials_parts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billofmaterials',
            name='parts',
            field=models.ManyToManyField(blank=True, through='warehouse.BOMParts', to='warehouse.stock'),
        ),
        migrations.AlterField(
            model_name='bomparts',
            name='part',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='warehouse.stock'),
        ),
    ]
