# Generated by Django 5.0.1 on 2026-01-08 09:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0029_remove_deliverycustomerpalette_customer_delivery_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockSupplySettlement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('settlement', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='warehouse.ordersettlement')),
                ('stock_supply', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='warehouse.stocksupply')),
            ],
        ),
    ]
