# Generated by Django 5.0.1 on 2026-01-08 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0030_stocksupplysettlement'),
    ]

    operations = [
        migrations.AddField(
            model_name='stocksupplysettlement',
            name='value',
            field=models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=12),
        ),
    ]
