# Generated by Django 5.0.1 on 2026-01-08 13:19

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0031_stocksupplysettlement_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stocksupply',
            name='value',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=7),
        ),
    ]
