# Generated by Django 5.0.1 on 2026-01-09 09:07

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0032_alter_stocksupply_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricelistitem',
            name='etc',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=4),
        ),
    ]
