# Generated by Django 5.0.1 on 2026-01-15 10:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0034_alter_deliveryspecialitem_price_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stocksupply',
            options={'ordering': ['-date']},
        ),
        migrations.CreateModel(
            name='StockSupplySell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('sell', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='warehouse.productsell3')),
                ('stock_supply', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='warehouse.stocksupply')),
            ],
            options={
                'ordering': ['-sell__date'],
            },
        ),
    ]
