# Generated by Django 5.0.1 on 2026-01-21 11:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0036_stocksupplysettlement_as_result'),
    ]

    operations = [
        migrations.CreateModel(
            name='BOM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='boms', to='warehouse.product')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='bom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='warehouse.bom'),
        ),
        migrations.CreateModel(
            name='BOMPart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=10)),
                ('bom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parts', to='warehouse.bom')),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='warehouse.stock')),
            ],
        ),
        migrations.AddConstraint(
            model_name='bom',
            constraint=models.UniqueConstraint(fields=('product', 'version'), name='uniq_bom_product_version'),
        ),
        migrations.AddConstraint(
            model_name='bompart',
            constraint=models.UniqueConstraint(fields=('bom', 'part'), name='uniq_bompart_bom_part'),
        ),
    ]
