# Generated by Django 5.0.1 on 2026-01-22 08:10

from django.db import migrations


# mapowanie Twoich aktualnych wartości -> docelowe
MAPPING = {
    "material": "material",
    "product": "product",
    "special": "special",

    "Material".lower(): "material",
    "Product".lower(): "product",
    "Special".lower(): "special",

    "Insert".lower(): "product",
    "Trellis".lower(): "product",
    "Spacer".lower(): "product",
    "Box".lower(): "product",
    "Trellis set".lower(): "product",
}

ALLOWED = {"material", "product", "special"}


def normalize_stocktype(apps, schema_editor):
    StockType = apps.get_model("warehouse", "StockType")

    for st in StockType.objects.all():
        raw = (st.stock_type or "")
        key = " ".join(raw.strip().split()).lower()  # trim + usuń podwójne spacje + lower

        new_val = MAPPING.get(key, "product")  # wszystko nieznane -> product
        if new_val not in ALLOWED:
            new_val = "product"

        if st.stock_type != new_val:
            st.stock_type = new_val
            st.save(update_fields=["stock_type"])


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0037_bom_order_bom_bompart_bom_uniq_bom_product_version_and_more'),  # <-- zostaw to co Django wpisało
    ]

    operations = [
        migrations.RunPython(normalize_stocktype, migrations.RunPython.noop),
    ]
