# Generated by Django 5.0.1 on 2026-01-22 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0038_normalize_stocktype'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stock',
            options={'ordering': ['stock_type__stock_type', 'name']},
        ),
    ]
