# Generated by Django 5.0.1 on 2026-01-22 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0039_alter_stock_options'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='warehousestock',
            constraint=models.UniqueConstraint(fields=('warehouse', 'stock'), name='uniq_warehouse_stock_pair'),
        ),
    ]
