# Generated by Django 5.0.1 on 2026-01-22 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0040_warehousestock_uniq_warehouse_stock_pair'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='stock',
            constraint=models.UniqueConstraint(fields=('stock_type', 'name'), name='uniq_stock_type_name'),
        ),
    ]
