# Generated by Django 5.0.1 on 2026-01-29 20:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0041_stock_uniq_stock_type_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehousestockhistory',
            name='sell',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='warehouse.productsell3'),
        ),
    ]
