# Generated by Django 5.0.1 on 2026-01-29 22:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0042_warehousestockhistory_sell'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductSellOrderPart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='warehouse.order')),
                ('sell', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_parts', to='warehouse.productsell3')),
            ],
            options={
                'unique_together': {('sell', 'order')},
            },
        ),
    ]
