# Generated by Django 5.0.1 on 2026-01-30 10:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0043_productsellorderpart'),
    ]

    operations = [
        migrations.AddField(
            model_name='productsell3',
            name='stock',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='warehouse.stock'),
        ),
        migrations.AlterField(
            model_name='productsell3',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='warehouse.product'),
        ),
    ]
