# Generated by Django 5.0.1 on 2026-01-30 11:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0044_productsell3_stock_alter_productsell3_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryitem',
            name='provider_code',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='deliveryitem',
            name='stock',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='warehouse.stock'),
        ),
        migrations.CreateModel(
            name='StockAlias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider_code', models.CharField(max_length=128)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.CharField(blank=True, max_length=256, null=True)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='warehouse.provider')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='aliases', to='warehouse.stock')),
            ],
            options={
                'indexes': [models.Index(fields=['provider', 'provider_code'], name='warehouse_s_provide_e35102_idx'), models.Index(fields=['stock'], name='warehouse_s_stock_i_47be46_idx')],
                'unique_together': {('provider', 'provider_code')},
            },
        ),
    ]
