# Generated by Django 5.0.1 on 2026-01-30 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0045_deliveryitem_provider_code_deliveryitem_stock_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='stockalias',
            name='warehouse_s_provide_e35102_idx',
        ),
        migrations.RenameField(
            model_name='deliveryitem',
            old_name='provider_code',
            new_name='provider_sku',
        ),
        migrations.RenameField(
            model_name='stockalias',
            old_name='provider_code',
            new_name='provider_sku',
        ),
        migrations.AlterUniqueTogether(
            name='stockalias',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='stockalias',
            name='dimensions',
            field=models.CharField(default='ok', max_length=64),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='stockalias',
            unique_together={('provider', 'provider_sku', 'dimensions')},
        ),
        migrations.AddIndex(
            model_name='stockalias',
            index=models.Index(fields=['provider', 'provider_sku', 'dimensions'], name='warehouse_s_provide_107318_idx'),
        ),
    ]
