# Generated by Django 5.0.1 on 2026-02-02 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0046_remove_stockalias_warehouse_s_provide_e35102_idx_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='stocksupply',
            constraint=models.UniqueConstraint(condition=models.Q(('delivery_item__isnull', False)), fields=('delivery_item',), name='uniq_supply_per_delivery_item'),
        ),
    ]
