# Generated by Django 5.0.1 on 2026-02-03 12:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0047_stocksupply_uniq_supply_per_delivery_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryspecialitem',
            name='provider_sku',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='deliveryspecialitem',
            name='stock',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='warehouse.stock'),
        ),
        migrations.AddField(
            model_name='stocksupply',
            name='delivery_special_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='warehouse.deliveryspecialitem'),
        ),
        migrations.AddConstraint(
            model_name='stocksupply',
            constraint=models.UniqueConstraint(condition=models.Q(('delivery_special_item__isnull', False)), fields=('delivery_special_item',), name='uniq_supply_per_delivery_special_item'),
        ),
    ]
