# Generated by Django 5.0.1 on 2026-02-20 14:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0050_warehousestockhistory_delta'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductPackaging',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('columns', models.PositiveIntegerField(default=0, help_text='Słupki')),
                ('layers', models.PositiveIntegerField(default=0, help_text='Warstwy')),
                ('qty_per_pack', models.PositiveIntegerField(default=0, help_text='Ilość w paczce')),
                ('qty_per_pallet', models.PositiveIntegerField(default=0, editable=False, help_text='Auto: columns * layers * qty_per_pack')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('palette', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='product_packagings', to='warehouse.palette')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='packaging', to='warehouse.product')),
            ],
            options={
                'verbose_name': 'Product packaging',
                'verbose_name_plural': 'Product packagings',
            },
        ),
    ]
