# Generated by Django 5.0.1 on 2026-03-27 14:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0005_alter_maintenancedeliveryitem_options_and_more'),
        ('warehouse', '0051_productpackaging'),
    ]

    operations = [
        migrations.AddField(
            model_name='stocksupply',
            name='maintenance_delivery_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='maintenance.maintenancedeliveryitem'),
        ),
        migrations.AddConstraint(
            model_name='stocksupply',
            constraint=models.UniqueConstraint(condition=models.Q(('maintenance_delivery_item__isnull', False)), fields=('maintenance_delivery_item',), name='uniq_supply_per_maintenance_delivery_item'),
        ),
    ]
