# Generated by Django 5.0.1 on 2026-03-30 11:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0007_maintenancepartusage_processed_and_more'),
        ('warehouse', '0052_stocksupply_maintenance_delivery_item_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehousestockhistory',
            name='maintenance_part_usage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='warehouse_history_rows', to='maintenance.maintenancepartusage'),
        ),
    ]
