# Generated by Django 5.0.1 on 2026-04-20 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0053_warehousestockhistory_maintenance_part_usage'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehouse',
            name='value',
            field=models.DecimalField(decimal_places=2, default='0.00', max_digits=12),
        ),
    ]
