# Generated by Django 5.0.1 on 2026-05-13 09:29

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0054_warehouse_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='stocksupply',
            name='area',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='stocksupply',
            name='volume',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=12),
        ),
    ]
