# Generated by Django 5.0.1 on 2026-07-02 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0055_stocksupply_area_stocksupply_volume'),
    ]

    operations = [
        migrations.AddField(
            model_name='productpackaging',
            name='additional_info',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
    ]
