# Generated by Django 5.0.1 on 2026-07-10 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0057_order_photopolymer_order_punch'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='photopolymer',
        ),
        migrations.RemoveField(
            model_name='order',
            name='punch',
        ),
    ]
