# Generated by Django 5.0.1 on 2026-07-23 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0059_shipmentunit'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='FEFCO_code',
            field=models.CharField(choices=[('200', '200'), ('201', '201'), ('202', '202'), ('203', '203'), ('215', '215'), ('301', '301'), ('409', '409'), ('410', '410'), ('421', '421'), ('427', '427'), ('471', '471')], default='201', max_length=4),
        ),
    ]
