# Generated by Django 5.0.1 on 2026-07-31 10:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0061_alter_product_fefco_code'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShipmentUnitHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shipment_unit_original_id', models.PositiveIntegerField()),
                ('quantity', models.PositiveIntegerField()),
                ('action', models.CharField(choices=[('UPDATE', 'Edycja'), ('DELETE', 'Usunięcie')], max_length=16)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shipment_unit_changes', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shipment_unit_history', to='warehouse.order')),
                ('palette', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='warehouse.palette')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='warehouse.product')),
                ('shipment_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='history', to='warehouse.shipmentunit')),
            ],
            options={
                'verbose_name': 'historia jednostki wysyłkowej',
                'verbose_name_plural': 'historie jednostek wysyłkowych',
                'ordering': ['-changed_at', '-id'],
            },
        ),
    ]
