# Generated by Django 5.0.1 on 2026-08-03 08:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0062_shipmentunithistory'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('draft', 'W trakcie załadunku'), ('confirmed', 'Potwierdzony'), ('cancelled', 'Anulowany')], default='draft', max_length=16)),
                ('car_number', models.CharField(blank=True, default='', max_length=32)),
                ('driver_name', models.CharField(blank=True, default='', max_length=128)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='confirmed_shipments', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_shipments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ShipmentItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scanned_at', models.DateTimeField(auto_now_add=True)),
                ('scanned_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='scanned_shipment_items', to=settings.AUTH_USER_MODEL)),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='warehouse.shipment')),
                ('shipment_unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shipment_items', to='warehouse.shipmentunit')),
            ],
            options={
                'ordering': ['scanned_at', 'id'],
            },
        ),
        migrations.AddField(
            model_name='shipment',
            name='shipment_units',
            field=models.ManyToManyField(related_name='shipments', through='warehouse.ShipmentItem', to='warehouse.shipmentunit'),
        ),
        migrations.AddConstraint(
            model_name='shipmentitem',
            constraint=models.UniqueConstraint(fields=('shipment_unit',), name='shipment_unit_used_only_once'),
        ),
        migrations.AddConstraint(
            model_name='shipmentitem',
            constraint=models.UniqueConstraint(fields=('shipment', 'shipment_unit'), name='unique_unit_in_shipment'),
        ),
        migrations.AddConstraint(
            model_name='shipment',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'draft')), fields=('created_by',), name='one_draft_shipment_per_user'),
        ),
    ]
