# Generated by Django 5.0.1 on 2026-09-21 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0063_shipment_shipmentitem_shipment_shipment_units_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='alter_name',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
