# Generated by Django 5.0.1 on 2026-09-21 16:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0064_product_alter_name'),
        ('warehousemanager', '0123_alter_photopolymer_identification_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipmentunit',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='shipment_customers', to='warehousemanager.buyer'),
        ),
    ]
