# Generated by Django 5.0.1 on 2026-09-23 09:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0065_shipmentunit_customer'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerStockItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minimum_quantity', models.PositiveIntegerField(default=0)),
                ('warehouse_stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_stock_items', to='warehouse.warehousestock')),
            ],
            options={
                'ordering': ['warehouse_stock__stock__name'],
            },
        ),
        migrations.CreateModel(
            name='CustomerStockList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='customer_stock_list', to=settings.AUTH_USER_MODEL)),
                ('warehouse_stocks', models.ManyToManyField(blank=True, related_name='customer_stock_lists', through='warehouse.CustomerStockItem', to='warehouse.warehousestock')),
            ],
        ),
        migrations.AddField(
            model_name='customerstockitem',
            name='stock_list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='warehouse.customerstocklist'),
        ),
        migrations.AddConstraint(
            model_name='customerstockitem',
            constraint=models.UniqueConstraint(fields=('stock_list', 'warehouse_stock'), name='unique_customer_stock_item'),
        ),
    ]
