# Generated by Django 3.2.4 on 2021-10-06 17:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('warehousemanager', '0087_alter_uservisitcounter_page'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_number', models.CharField(max_length=32, unique=True)),
                ('cardboard', models.CharField(blank=True, max_length=32)),
                ('cardboard_dimensions', models.CharField(blank=True, max_length=32)),
                ('dimensions', models.CharField(blank=True, max_length=32, null=True)),
                ('quantity', models.PositiveIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('UNCOMPLETED', 'UNCOMPLETED'), ('COMPLETED', 'COMPLETED')], default='UNCOMPLETED', max_length=32)),
                ('completed', models.DateTimeField(blank=True, null=True)),
                ('priority', models.BooleanField(default=False)),
                ('notes', models.CharField(blank=True, max_length=1000, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehousemanager.buyer')),
            ],
        ),
        migrations.CreateModel(
            name='WorkStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=48)),
            ],
        ),
        migrations.CreateModel(
            name='ProductionUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(unique=True)),
                ('status', models.CharField(choices=[('NOT STARTED', 'NOT STARTED'), ('IN PROGRESS', 'IN PROGRESS'), ('FINISHED', 'FINISHED')], default='NOT STARTED', max_length=32)),
                ('start', models.DateTimeField(blank=True, null=True)),
                ('end', models.DateTimeField(blank=True, null=True)),
                ('notes', models.CharField(blank=True, max_length=1000, null=True)),
                ('persons', models.ManyToManyField(to='warehousemanager.Person')),
                ('production_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production.productionorder')),
                ('work_station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production.workstation')),
            ],
        ),
    ]
