# Generated by Django 3.2.4 on 2021-10-06 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productionunit',
            name='order',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='productionunit',
            name='status',
            field=models.CharField(choices=[('NOT STARTED', 'NOT STARTED'), ('PLANNED', 'PLANNED'), ('IN PROGRESS', 'IN PROGRESS'), ('FINISHED', 'FINISHED')], default='NOT STARTED', max_length=32),
        ),
    ]
