# Generated by Django 3.2.4 on 2021-10-06 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0002_auto_20211006_1954'),
    ]

    operations = [
        migrations.AddField(
            model_name='productionunit',
            name='quantity_end',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='productionunit',
            name='quantity_start',
            field=models.IntegerField(null=True),
        ),
    ]
