# Generated by Django 3.2.4 on 2021-10-06 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0003_auto_20211006_1959'),
    ]

    operations = [
        migrations.AddField(
            model_name='productionunit',
            name='estimated_time',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='productionorder',
            name='status',
            field=models.CharField(choices=[('UNCOMPLETED', 'UNCOMPLETED'), ('PLANNED', 'PLANNED'), ('COMPLETED', 'COMPLETED')], default='UNCOMPLETED', max_length=32),
        ),
        migrations.AlterField(
            model_name='productionunit',
            name='quantity_end',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='productionunit',
            name='quantity_start',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
