# Generated by Django 3.2.4 on 2021-10-07 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0004_auto_20211006_2316'),
    ]

    operations = [
        migrations.AddField(
            model_name='productionunit',
            name='sequence',
            field=models.IntegerField(default=1),
        ),
    ]
