# Generated by Django 3.2.4 on 2021-10-07 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehousemanager', '0087_alter_uservisitcounter_page'),
        ('production', '0005_productionunit_sequence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productionunit',
            name='persons',
            field=models.ManyToManyField(blank=True, null=True, to='warehousemanager.Person'),
        ),
    ]
