# Generated by Django 3.2.4 on 2021-10-15 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehousemanager', '0088_person_occupancy_type'),
        ('production', '0006_alter_productionunit_persons'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productionorder',
            name='status',
            field=models.CharField(choices=[('UNCOMPLETED', 'UNCOMPLETED'), ('COMPLETED', 'COMPLETED'), ('PLANNED', 'PLANNED'), ('FINISHED', 'FINISHED')], default='UNCOMPLETED', max_length=32),
        ),
        migrations.AlterField(
            model_name='productionunit',
            name='persons',
            field=models.ManyToManyField(blank=True, to='warehousemanager.Person'),
        ),
    ]
