# Generated by Django 3.2.9 on 2022-06-21 09:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('warehousemanager', '0090_alter_absence_absence_type'),
        ('production', '0007_auto_20211015_1954'),
    ]

    operations = [
        migrations.AddField(
            model_name='productionunit',
            name='polymer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='warehousemanager.photopolymer'),
        ),
        migrations.AddField(
            model_name='productionunit',
            name='punch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='warehousemanager.punch'),
        ),
    ]
