# Generated by Django 3.2.16 on 2023-03-01 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0010_alter_productionorder_add_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productionorder',
            name='add_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
