# Generated by Django 3.1.3 on 2023-07-11 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0012_auto_20230615_1859'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productionorder',
            options={'ordering': ['add_date']},
        ),
        migrations.AlterField(
            model_name='productionorder',
            name='add_date',
            field=models.DateTimeField(auto_created=True),
        ),
    ]
