# Generated by Django 3.1.3 on 2023-07-18 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0013_auto_20230711_2227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productionorder',
            name='add_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
