# Generated by Django 3.1.3 on 2023-07-18 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0014_auto_20230718_1041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productionorder',
            name='add_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
