# Generated by Django 5.0.1 on 2024-02-27 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0017_auto_20230920_1300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productionorder',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='productionorder',
            name='status',
            field=models.CharField(choices=[('ORDERED', 'ORDERED'), ('UNCOMPLETED', 'UNCOMPLETED'), ('COMPLETED', 'COMPLETED'), ('PLANNED', 'PLANNED'), ('FINISHED', 'FINISHED'), ('ARCHIVED', 'ARCHIVED')], default='UNCOMPLETED', max_length=32),
        ),
        migrations.AlterField(
            model_name='productionunit',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='workstation',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
