# Generated by Django 5.0.1 on 2025-06-27 10:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0018_alter_productionorder_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeeklyPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week', models.PositiveIntegerField()),
                ('year', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'unique_together': {('week', 'year')},
            },
        ),
        migrations.CreateModel(
            name='ProductionTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('production_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production.productionunit')),
                ('work_station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production.workstation')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='production.weeklyplan')),
            ],
            options={
                'ordering': ['start'],
            },
        ),
    ]
