# Generated by Django 5.0.1 on 2025-06-27 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0019_weeklyplan_productiontask'),
    ]

    operations = [
        migrations.AddField(
            model_name='productionunit',
            name='required_helpers',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='productionunit',
            name='required_operators',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
