# Generated by Django 5.0.1 on 2025-06-27 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0020_productionunit_required_helpers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productiontask',
            name='is_temporary',
            field=models.BooleanField(default=False),
        ),
    ]
