# Generated by Django 5.0.1 on 2025-06-27 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0021_productiontask_is_temporary'),
        ('warehousemanager', '0112_workstationqualification_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productiontask',
            name='persons',
            field=models.ManyToManyField(blank=True, related_name='tasks', to='warehousemanager.person'),
        ),
    ]
