# Generated by Django 5.0.1 on 2025-07-02 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0022_productiontask_persons'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='productionunit',
            unique_together={('production_order', 'sequence')},
        ),
    ]
