# Generated by Django 5.0.1 on 2025-07-02 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0023_alter_productionunit_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='workstation',
            name='energy',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
