# Generated by Django 5.0.1 on 2025-07-03 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0024_workstation_energy'),
    ]

    operations = [
        migrations.AddField(
            model_name='workstation',
            name='lifetime',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='workstation',
            name='value',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
