# Generated by Django 5.0.1 on 2025-11-28 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0025_workstation_lifetime_workstation_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='workstation',
            name='setup_time',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
