# Generated by Django 5.0.1 on 2026-03-26 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0026_workstation_setup_time'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workstation',
            options={'ordering': ['name']},
        ),
    ]
