# Generated by Django 5.0.1 on 2026-07-10 09:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0027_alter_workstation_options'),
        ('warehousemanager', '0119_alter_person_occupancy_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='productionorder',
            name='photopolymer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='warehousemanager.photopolymer'),
        ),
        migrations.AddField(
            model_name='productionorder',
            name='punch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='warehousemanager.punch'),
        ),
    ]
