# Generated by Django 5.0.1 on 2024-08-28 08:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('warehousemanager', '0105_remove_person_date26_alter_person_occupancy_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tax_number', models.CharField(blank=True, max_length=32, null=True)),
                ('country', models.CharField(default='POLAND', max_length=32)),
                ('city', models.CharField(blank=True, max_length=32, null=True)),
                ('zip_code', models.CharField(blank=True, max_length=8, null=True)),
                ('address', models.CharField(blank=True, max_length=32, null=True)),
                ('date_add', models.DateTimeField(auto_now_add=True)),
                ('date_edit', models.DateTimeField(auto_now=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='warehousemanager.buyer')),
                ('representative', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='warehousemanager.person')),
            ],
        ),
    ]
