# Generated by Django 5.0.1 on 2026-03-27 08:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0002_maintenancesupplier_machinepart_supplier_code_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MachinePartSupplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier_code', models.CharField(blank=True, max_length=100, null=True)),
                ('is_preferred', models.BooleanField(default=False)),
                ('lead_time_days', models.PositiveIntegerField(blank=True, null=True)),
                ('notes', models.CharField(blank=True, max_length=255, null=True)),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='part_suppliers', to='maintenance.machinepart')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='supplier_parts', to='maintenance.maintenancesupplier')),
            ],
            options={
                'ordering': ['-is_preferred', 'supplier__name'],
                'unique_together': {('part', 'supplier')},
            },
        ),
    ]
