# Generated by Django 5.0.1 on 2026-03-27 12:54

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0003_machinepartsupplier'),
        ('warehouse', '0051_productpackaging'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenanceDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_date', models.DateField()),
                ('document_number', models.CharField(blank=True, max_length=100, null=True)),
                ('invoice_number', models.CharField(blank=True, max_length=100, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('is_received', models.BooleanField(default=False)),
                ('received_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='maintenance_deliveries', to=settings.AUTH_USER_MODEL)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deliveries', to='maintenance.maintenancesupplier')),
            ],
            options={
                'ordering': ['-delivery_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='MaintenanceDeliveryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('unit_price_net', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('total_price_net', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('supplier_code', models.CharField(blank=True, max_length=100, null=True)),
                ('notes', models.CharField(blank=True, max_length=255, null=True)),
                ('delivery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='maintenance.maintenancedelivery')),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='delivery_items', to='maintenance.machinepart')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='maintenance_delivery_items', to='warehouse.warehouse')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
