# Generated by Django 5.0.1 on 2026-03-27 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0004_maintenancedelivery_maintenancedeliveryitem'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='maintenancedeliveryitem',
            options={},
        ),
        migrations.AddField(
            model_name='maintenancedeliveryitem',
            name='processed',
            field=models.BooleanField(default=False),
        ),
    ]
