# Generated by Django 5.0.1 on 2026-03-30 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0005_alter_maintenancedeliveryitem_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='maintenancedeliveryitem',
            options={'ordering': ['id']},
        ),
        migrations.AddField(
            model_name='machinepart',
            name='image_urls',
            field=models.TextField(blank=True, help_text='Jedno zdjęcie w jednej linii lub oddzielone przecinkami/średnikami', null=True),
        ),
    ]
