# Generated by Django 5.0.1 on 2026-03-30 11:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0006_alter_maintenancedeliveryitem_options_and_more'),
        ('warehouse', '0052_stocksupply_maintenance_delivery_item_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenancepartusage',
            name='processed',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='MaintenancePartUsageSupply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('stock_supply', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='maintenance_usage_rows', to='warehouse.stocksupply')),
                ('usage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supply_rows', to='maintenance.maintenancepartusage')),
            ],
            options={
                'ordering': ['stock_supply__date', 'stock_supply__id'],
            },
        ),
    ]
