from django.contrib import admin
from warehousemanager.models import *

admin.site.register(Order)
admin.site.register(Person)
admin.site.register(CardboardProvider)
admin.site.register(OrderItem)
admin.site.register(Buyer)
admin.site.register(OrderItemQuantity)
admin.site.register(Delivery)
admin.site.register(Machine)
admin.site.register(Note)
admin.site.register(Absence)
admin.site.register(Holiday)
admin.site.register(ExtraHour)
admin.site.register(Punch)
admin.site.register(PunchProduction)
admin.site.register(ProductionProcess)
admin.site.register(SpreadsheetCopy)
admin.site.register(DailyReport)
admin.site.register(Photopolymer)
admin.site.register(PhotopolymerService)
admin.site.register(UserVisitCounter)
admin.site.register(Color)
admin.site.register(ColorBucket)
admin.site.register(Palette)
admin.site.register(PaletteQuantity)
admin.site.register(Contract)
admin.site.register(Reminder)
admin.site.register(PaletteCustomer)
admin.site.register(Message)
admin.site.register(Cloth)
admin.site.register(WorkerWorkWear)
admin.site.register(WorkReminder)
admin.site.register(GluerNumber)
admin.site.register(WorkStationQualification)
