from django.contrib import admin
from warehousemanager.models import *

admin.site.register(Order)
admin.site.register(Person)
admin.site.register(CardboardProvider)
admin.site.register(OrderItem)
admin.site.register(Buyer)
admin.site.register(OrderItemQuantity)
admin.site.register(Delivery)
admin.site.register(Machine)
admin.site.register(Note)
admin.site.register(Absence)
admin.site.register(Holiday)
admin.site.register(ExtraHour)
admin.site.register(Punch)
admin.site.register(PunchProduction)
admin.site.register(ProductionProcess)
admin.site.register(SpreadsheetCopy)
admin.site.register(DailyReport)
