# Generated by Django 5.0.1 on 2024-11-27 10:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0002_remove_stocksupply_weight'),
    ]

    operations = [
        migrations.CreateModel(
            name='WarehouseStockHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_before', models.PositiveIntegerField(default=0)),
                ('quantity_after', models.PositiveIntegerField(default=0)),
                ('date', models.DateField(blank=True, null=True)),
                ('order_settlement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='warehouse.ordersettlement')),
                ('stock_supply', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='warehouse.stocksupply')),
                ('warehouse_stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warehouse_stock', to='warehouse.warehousestock')),
            ],
        ),
    ]
