# Generated by Django 3.1.3 on 2023-07-11 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0002_auto_20230710_2218'),
    ]

    operations = [
        migrations.AddField(
            model_name='productproduction',
            name='quantity',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
