# Generated by Django 3.2.16 on 2023-02-19 16:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cardboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=16)),
                ('layers', models.CharField(choices=[(2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7)], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('shortcut', models.CharField(max_length=32, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Karton', 'Karton'), ('Przekładka', 'Przekładka'), ('Taśma', 'Taśma'), ('Folia Stretch', 'Folia Stretch'), ('Folia Bąbelkowa', 'Folia Bąbelkowa'), ('Usługa', 'Usługa'), ('Paleta', 'Paleta'), ('Produkt', 'Produkt')], max_length=64)),
                ('description', models.CharField(default='', max_length=256)),
                ('dimensions', models.CharField(blank=True, max_length=128, null=True)),
                ('cardboard', models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('F', 'F'), ('BC', 'BC'), ('EB', 'EB'), ('EC', 'EC'), ('EE', 'EE')], max_length=16, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('shortcut', models.CharField(max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='OrderUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('delivered', models.BooleanField(default=False)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='orders.customer')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='orders.product')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='orders.customer')),
            ],
        ),
        migrations.CreateModel(
            name='DeliveryUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('delivery', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='orders.delivery')),
                ('order_unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='orders.orderunit')),
            ],
        ),
        migrations.AddField(
            model_name='delivery',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='orders.supplier'),
        ),
        migrations.CreateModel(
            name='CardboardPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField()),
                ('active_from', models.DateField(blank=True, null=True)),
                ('active_until', models.DateField(blank=True, null=True)),
                ('cardboard', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='orders.cardboard')),
            ],
        ),
        migrations.AddField(
            model_name='cardboard',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='orders.supplier'),
        ),
    ]
