# Generated by Django 5.0.1 on 2026-09-26 06:55

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('production', '0030_productionorderpriorityhistory'),
        ('warehouse', '0066_customerstockitem_customerstocklist_and_more'),
        ('warehousemanager', '0123_alter_photopolymer_identification_number'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CardboardGrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.CharField(help_text='Indeks tektury u dostawcy', max_length=128)),
                ('layers', models.PositiveSmallIntegerField()),
                ('flute', models.CharField(max_length=8)),
                ('gsm', models.PositiveIntegerField()),
                ('ect', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('composition', models.CharField(blank=True, default='', help_text='Skład surowcowy wg dostawcy', max_length=255)),
                ('cover', models.CharField(blank=True, choices=[('GREY', 'Szara'), ('WHITE_ONE_SIDE', 'Jednostronnie biała'), ('WHITE_TWO_SIDES', 'Dwustronnie biała'), ('OTHER', 'Inna')], max_length=32, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cardboard_grades', to='warehouse.provider')),
            ],
            options={
                'ordering': ['provider', 'layers', 'flute', 'gsm'],
            },
        ),
        migrations.CreateModel(
            name='CardboardOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=64)),
                ('order_date', models.DateField()),
                ('status', models.CharField(choices=[('DRAFT', 'Robocze'), ('SENT', 'Wysłane'), ('PARTIALLY_RECEIVED', 'Częściowo dostarczone'), ('RECEIVED', 'Dostarczone'), ('CANCELLED', 'Anulowane')], db_index=True, default='DRAFT', max_length=32)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_cardboard_orders', to=settings.AUTH_USER_MODEL)),
                ('legacy_warehouse_order', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='new_cardboard_order', to='warehouse.order')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='new_cardboard_orders', to='warehouse.provider')),
            ],
            options={
                'ordering': ['-order_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='CardboardPriceList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(blank=True, default='', max_length=128)),
                ('valid_from', models.DateField(db_index=True)),
                ('valid_to', models.DateField(blank=True, db_index=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_cardboard_price_lists', to=settings.AUTH_USER_MODEL)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cardboard_price_lists', to='warehouse.provider')),
            ],
            options={
                'ordering': ['-valid_from', '-id'],
            },
        ),
        migrations.CreateModel(
            name='CardboardPriceListItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider_status', models.CharField(choices=[('STANDARD', 'Standard'), ('NON_STANDARD', 'Niestandardowa'), ('SPECIAL', 'Specjalna'), ('OTHER', 'Inna')], default='STANDARD', max_length=32)),
                ('provider_status_raw', models.CharField(blank=True, default='', max_length=64)),
                ('cardboard', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='price_list_items', to='orders.cardboardgrade')),
                ('price_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.cardboardpricelist')),
            ],
        ),
        migrations.CreateModel(
            name='CardboardOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sheet_length', models.PositiveIntegerField()),
                ('sheet_width', models.PositiveIntegerField()),
                ('quantity', models.PositiveIntegerField()),
                ('price_per_1000_m2', models.DecimalField(decimal_places=2, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cardboard', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='orders.cardboardgrade')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.cardboardorder')),
                ('price_list_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='orders.cardboardpricelistitem')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='CardboardPriceTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_area_m2', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('max_area_m2', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('price_per_1000_m2', models.DecimalField(decimal_places=2, max_digits=12)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_tiers', to='orders.cardboardpricelistitem')),
            ],
            options={
                'ordering': ['min_area_m2'],
            },
        ),
        migrations.CreateModel(
            name='CustomerOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_order_number', models.CharField(blank=True, db_index=True, max_length=64, null=True)),
                ('quantity', models.PositiveIntegerField(help_text='Ilość produktu zamówiona przez klienta')),
                ('order_date', models.DateField(blank=True, help_text='Data zamówienia klienta', null=True)),
                ('requested_delivery_date', models.DateField(blank=True, help_text='Oczekiwany termin dostawy produktu', null=True)),
                ('status', models.CharField(choices=[('NEW', 'Nowe'), ('MATERIAL_PENDING', 'Oczekuje na materiał'), ('MATERIAL_READY', 'Materiał gotowy'), ('READY_FOR_PRODUCTION', 'Gotowe do produkcji'), ('IN_PRODUCTION', 'W produkcji'), ('COMPLETED', 'Zakończone'), ('CANCELLED', 'Anulowane')], db_index=True, default='NEW', max_length=32)),
                ('priority', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Niski'), (2, 'Wysoki'), (3, 'Krytyczny')], null=True)),
                ('priority_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_customer_orders', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='customer_orders', to='warehousemanager.buyer')),
                ('legacy_production_order', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='new_customer_order', to='production.productionorder')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='customer_orders', to='warehouse.product')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_customer_orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='MaterialRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sheet_length', models.PositiveIntegerField(help_text='Długość arkusza w mm')),
                ('sheet_width', models.PositiveIntegerField(help_text='Szerokość arkusza w mm')),
                ('pieces_per_sheet', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=10)),
                ('required_sheet_quantity', models.PositiveIntegerField(default=0, help_text='Ilość potrzebnych arkuszy')),
                ('layers', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('flute', models.CharField(blank=True, default='', max_length=8)),
                ('min_gsm', models.PositiveIntegerField(blank=True, null=True)),
                ('min_ect', models.DecimalField(blank=True, decimal_places=2, help_text='Minimalne ECT kN/m', max_digits=8, null=True)),
                ('cover', models.CharField(blank=True, choices=[('GREY', 'Szara'), ('WHITE_ONE_SIDE', 'Jednostronnie biała'), ('WHITE_TWO_SIDES', 'Dwustronnie biała'), ('OTHER', 'Inna')], max_length=32, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='material_requirements', to='orders.customerorder')),
            ],
            options={
                'ordering': ['customer_order_id', 'id'],
            },
        ),
        migrations.CreateModel(
            name='MaterialAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('STOCK', 'Magazyn'), ('PURCHASE', 'Zakup')], max_length=16)),
                ('quantity', models.PositiveIntegerField(help_text='Ilość arkuszy przeznaczonych na zlecenie')),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cardboard_order_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='material_allocations', to='orders.cardboardorderitem')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='material_allocations', to=settings.AUTH_USER_MODEL)),
                ('stock_supply', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='order_material_allocations', to='warehouse.stocksupply')),
                ('requirement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='orders.materialrequirement')),
            ],
            options={
                'ordering': ['requirement', 'id'],
            },
        ),
        migrations.AddField(
            model_name='cardboardorderitem',
            name='requirement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_items', to='orders.materialrequirement'),
        ),
        migrations.AddConstraint(
            model_name='cardboardgrade',
            constraint=models.UniqueConstraint(fields=('provider', 'index'), name='orders_unique_provider_cardboard_index'),
        ),
        migrations.AddConstraint(
            model_name='cardboardorder',
            constraint=models.UniqueConstraint(fields=('provider', 'number'), name='orders_unique_provider_purchase_number'),
        ),
        migrations.AddConstraint(
            model_name='cardboardpricelistitem',
            constraint=models.UniqueConstraint(fields=('price_list', 'cardboard'), name='orders_unique_price_list_cardboard'),
        ),
        migrations.AddIndex(
            model_name='customerorder',
            index=models.Index(fields=['customer', 'created_at'], name='orders_customer_created_idx'),
        ),
        migrations.AddIndex(
            model_name='customerorder',
            index=models.Index(fields=['status', 'priority'], name='orders_status_priority_idx'),
        ),
        migrations.AddConstraint(
            model_name='materialallocation',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('source', 'STOCK'), ('stock_supply__isnull', False), ('cardboard_order_item__isnull', True)), models.Q(('source', 'PURCHASE'), ('stock_supply__isnull', True), ('cardboard_order_item__isnull', False)), _connector='OR'), name='orders_valid_material_allocation_source'),
        ),
    ]
