# Generated by Django 5.0.1 on 2026-09-26 21:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
        ('production', '0030_productionorderpriorityhistory'),
        ('warehouse', '0066_customerstockitem_customerstocklist_and_more'),
        ('warehousemanager', '0123_alter_photopolymer_identification_number'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerOrderSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField(unique=True)),
                ('last_number', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='customerorder',
            name='customer_order_number',
        ),
        migrations.AddField(
            model_name='customerorder',
            name='number',
            field=models.PositiveIntegerField(blank=True, db_index=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='customerorder',
            name='year',
            field=models.PositiveSmallIntegerField(blank=True, db_index=True, editable=False, null=True),
        ),
        migrations.AddConstraint(
            model_name='customerorder',
            constraint=models.UniqueConstraint(fields=('year', 'number'), name='orders_unique_customer_order_number_year'),
        ),
    ]
