# Generated by Django 3.2.16 on 2023-02-19 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardboard',
            name='ECT',
            field=models.DecimalField(decimal_places=2, default=2, max_digits=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cardboard',
            name='wave',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('F', 'F'), ('BC', 'BC'), ('EB', 'EB'), ('EC', 'EC'), ('EE', 'EE')], default='A', max_length=8),
            preserve_default=False,
        ),
    ]
