# Generated by Django 5.0.1 on 2026-09-28 11:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_customerordersequence_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialRequirementScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position_mm', models.PositiveIntegerField(help_text='Pozycja liczona na szerokości arkusza.', verbose_name='Pozycja bigu [mm]')),
                ('requirement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='orders.materialrequirement')),
            ],
            options={
                'ordering': ['position_mm'],
            },
        ),
        migrations.AddConstraint(
            model_name='materialrequirementscore',
            constraint=models.UniqueConstraint(fields=('requirement', 'position_mm'), name='orders_unique_requirement_score'),
        ),
    ]
