# Generated by Django 3.2.16 on 2023-02-20 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20230219_1639'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardboardprice',
            name='currency',
            field=models.CharField(default='PLN', max_length=16),
        ),
        migrations.AlterField(
            model_name='cardboard',
            name='layers',
            field=models.CharField(choices=[('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7')], max_length=1),
        ),
    ]
