# Generated by Django 3.2.16 on 2023-02-20 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20230220_0004'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cardboard',
            old_name='ECT',
            new_name='ect',
        ),
        migrations.AddField(
            model_name='cardboard',
            name='grammage',
            field=models.IntegerField(default=12),
            preserve_default=False,
        ),
    ]
