# Generated by Django 5.0.1 on 2026-09-28 12:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_materialrequirementscore_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardboardOrderItemScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position_mm', models.PositiveIntegerField()),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='orders.cardboardorderitem')),
            ],
            options={
                'ordering': ['position_mm'],
            },
        ),
        migrations.AddConstraint(
            model_name='cardboardorderitemscore',
            constraint=models.UniqueConstraint(fields=('order_item', 'position_mm'), name='orders_unique_order_item_score'),
        ),
    ]
