# Generated by Django 5.0.1 on 2026-09-29 07:53

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_cardboardorderitemscore_and_more'),
        ('warehouse', '0066_customerstockitem_customerstocklist_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductMaterialRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sheet_length', models.PositiveIntegerField(help_text='Długość arkusza w mm')),
                ('sheet_width', models.PositiveIntegerField(help_text='Szerokość arkusza w mm')),
                ('pieces_per_sheet', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=10)),
                ('layers', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('flute', models.CharField(blank=True, default='', max_length=8)),
                ('min_gsm', models.PositiveIntegerField(blank=True, null=True)),
                ('min_ect', models.DecimalField(blank=True, decimal_places=2, help_text='Minimalne ECT kN/m', max_digits=8, null=True)),
                ('cover', models.CharField(blank=True, choices=[('GREY', 'Szara'), ('WHITE_ONE_SIDE', 'Jednostronnie biała'), ('WHITE_TWO_SIDES', 'Dwustronnie biała'), ('OTHER', 'Inna')], max_length=32, null=True)),
                ('scores', models.CharField(blank=True, default='', help_text='Bigi, np. 100/200/100', max_length=128)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='material_requirement_template', to='warehouse.product')),
            ],
        ),
    ]
