# Generated by Django 3.2.16 on 2023-02-20 00:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_auto_20230220_0008'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderunit',
            name='customer',
        ),
        migrations.AddField(
            model_name='orderunit',
            name='order',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='orders.order'),
            preserve_default=False,
        ),
    ]
