# Generated by Django 3.2.16 on 2023-02-24 19:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_alter_order_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardboardPurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dimensions', models.CharField(max_length=16)),
                ('ordered_quantity', models.IntegerField()),
                ('delivered_quantity', models.IntegerField(blank=True, null=True)),
                ('price_1000', models.IntegerField()),
                ('cardboard', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='orders.cardboard')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='orders.supplier')),
            ],
        ),
    ]
