# Generated by Django 3.1.3 on 2023-07-03 10:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('warehousemanager', '0091_auto_20230615_1909'),
        ('orders', '0011_auto_20230703_0818'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductSell',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('date', models.DateField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='warehousemanager.buyer')),
                ('product_price', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='orders.productprice')),
            ],
        ),
        migrations.CreateModel(
            name='CardboardPurchase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('dimensions', models.CharField(max_length=16)),
                ('ordered_quantity', models.IntegerField()),
                ('delivered_quantity', models.IntegerField(blank=True, null=True)),
                ('price_1000', models.IntegerField()),
                ('cardboard', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='orders.cardboard')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='orders.supplier')),
            ],
        ),
    ]
