# Generated by Django 5.0.1 on 2024-02-27 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_customer_delivery_remove_product_cardboard_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderproduct',
            name='realized',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='orderproduct',
            name='deadline',
            field=models.DateField(blank=True, null=True),
        ),
    ]
