# Generated by Django 5.0.1 on 2024-02-27 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0014_orderproduct_realized_alter_orderproduct_deadline'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderproduct',
            name='cardboard',
            field=models.BooleanField(default=False),
        ),
    ]
