# Generated by Django 5.0.1 on 2024-04-18 12:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0015_orderproduct_cardboard'),
    ]

    operations = [
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('shortcut', models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='CardboardOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=32)),
                ('order_date', models.DateField()),
                ('delivery_date', models.DateField(blank=True, null=True)),
                ('production_process', models.CharField(choices=[('ROT + SKL', 'ROT + SKL'), ('SLO + SKL', 'SLO + SKL')], max_length=128)),
                ('print', models.CharField(blank=True, max_length=64, null=True)),
                ('dimension_1', models.PositiveIntegerField()),
                ('dimension_2', models.PositiveIntegerField()),
                ('quantity', models.PositiveIntegerField()),
                ('delivered_quantity', models.PositiveIntegerField(default=0)),
                ('scores', models.CharField(blank=True, max_length=64, null=True)),
                ('specification', models.CharField(blank=True, max_length=128, null=True)),
                ('dimensions', models.CharField(blank=True, max_length=64, null=True)),
                ('name', models.CharField(blank=True, max_length=64, null=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='orders.customer')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='orders.provider')),
            ],
        ),
    ]
