# Generated by Django 5.0.1 on 2024-05-15 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0017_cardboardorder_product_product_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='finished',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='customers',
            field=models.CharField(blank=True, null=True),
        ),
    ]
