# Generated by Django 5.0.1 on 2026-09-24 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0018_order_finished_product_customers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cardboardorder',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='cardboardorder',
            name='product',
        ),
        migrations.RemoveField(
            model_name='cardboardorder',
            name='provider',
        ),
        migrations.RemoveField(
            model_name='order',
            name='customer',
        ),
        migrations.DeleteModel(
            name='Delivery',
        ),
        migrations.RemoveField(
            model_name='orderproduct',
            name='order',
        ),
        migrations.RemoveField(
            model_name='orderproduct',
            name='product',
        ),
        migrations.DeleteModel(
            name='CardboardOrder',
        ),
        migrations.DeleteModel(
            name='Provider',
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='OrderProduct',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
