# Generated by Django 5.0.1 on 2024-05-15 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0018_order_finished_product_customers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='customers',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
