# Generated by Django 3.1.3 on 2023-06-16 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveries', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[('PLANOWANA DOSTAWA', 'PLANOWANA DOSTAWA'), ('ZREALIZOWANA DOSTAWA', 'ZREALIZOWANA DOSTAWA'), ('SPOTKANIE', 'SPOTKANIE'), ('INNE', 'INNE')], default='INNE', max_length=32),
            preserve_default=False,
        ),
    ]
