# Generated by Django 3.1.3 on 2023-07-03 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveries', '0002_auto_20230616_0609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[('PLANOWANA DOSTAWA', 'PLANOWANA DOSTAWA'), ('ZREALIZOWANA DOSTAWA', 'ZREALIZOWANA DOSTAWA'), ('SPOTKANIE', 'SPOTKANIE'), ('ODBIÓR OSOBISTY', 'ODBIÓR OSOBISTY'), ('INNE', 'INNE')], max_length=32),
        ),
    ]
