# Generated by Django 5.0.1 on 2024-06-20 11:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveries', '0004_provider_delivery_deliveryitem'),
        ('orders', '0018_order_finished_product_customers'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryitem',
            name='cardboard_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='orders.cardboardorder'),
        ),
    ]
