# Generated by Django 5.0.1 on 2025-09-05 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deliveries', '0006_alter_event_event_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliveryitem',
            name='delivery',
        ),
        migrations.RemoveField(
            model_name='deliveryitem',
            name='cardboard_order',
        ),
        migrations.RemoveField(
            model_name='deliveryitem',
            name='order_item',
        ),
        migrations.DeleteModel(
            name='Delivery',
        ),
        migrations.DeleteModel(
            name='DeliveryItem',
        ),
    ]
