# Generated by Django 5.0.1 on 2026-09-24 22:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deliveries', '0007_remove_deliveryitem_delivery_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Provider',
        ),
    ]
